#include "../../GICommon.hlsl"
#pragma kernel CullObjectToClipmap

cbuffer _Params
{
    float4 _CascadeCenter;
    float4 _CascadeSize;
    float4 _CascadeResolution;
    float4 _UpdateChunkResolution;
    int _NumObjects;
    int _NumUpdateChunks;
    int _NumThreadsForCulling;
    int _MaxObjectNumPerUpdateChunk;
};

RWStructuredBuffer<int> _RWClipmapCullingResult;
RWStructuredBuffer<int> _RWClipmapObjectCounter;

groupshared bool gs_ThreadValidMask[8];
groupshared bool gs_ThreadCullingResult[8];
groupshared int gs_ThreadWriteIndex[8];

bool IsObjectPassCulling(int groupThreadIndex)
{
    bool validThread = gs_ThreadValidMask[groupThreadIndex];
    bool intersectObject = gs_ThreadCullingResult[groupThreadIndex];
    return validThread && intersectObject;
}

[numthreads(8, 1, 1)]
void CullObjectToClipmap(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID)
{
    int groupThreadIndex = groupThreadId.x;
    int objectIndex = threadId.x;

    // clamp the index, mark invalid thread
    gs_ThreadValidMask[groupThreadIndex] = objectIndex < _NumObjects;
    objectIndex = min(objectIndex, _NumObjects - 1);
    
    // 1. do culling
    ObjectInfo objectInfo = _ObjectsInfo[objectIndex];
    gs_ThreadCullingResult[groupThreadIndex] = ObjectIntersectAABB(objectInfo, _CascadeCenter, _CascadeSize);

    GroupMemoryBarrierWithGroupSync();

    // 2. allocate space in culling result array
    if (groupThreadIndex == 0)
    {
        int visibleObjectCounter = 0;
        for (int i = 0; i < 8; i++)
        {
            if (IsObjectPassCulling(i))
            {
                visibleObjectCounter += 1;
            }
        }

        int startIndex = 0;
        InterlockedAdd(_RWClipmapObjectCounter[0], visibleObjectCounter, startIndex);

        for (int j = 0; j < 8; j++)
        {
            if (IsObjectPassCulling(j))
            {
                gs_ThreadWriteIndex[j] = startIndex;
                startIndex += 1;
            }
        }
    }

    GroupMemoryBarrierWithGroupSync();

     // 3. write into culling result
    int writeIndex = gs_ThreadWriteIndex[groupThreadIndex];
    if (IsObjectPassCulling(groupThreadIndex))
    {
        _RWClipmapCullingResult[writeIndex] = objectIndex;
    }
}

#pragma kernel BuildUpdateChunkCullingIndirectArgs

StructuredBuffer<int> _ClipmapObjectCounter;
RWStructuredBuffer<int> _RWIndirectArgs;

[numthreads(1, 1, 1)]
void BuildUpdateChunkCullingIndirectArgs()
{
    _RWIndirectArgs[0] = ceil(float(_ClipmapObjectCounter[0]) / float(_NumThreadsForCulling));
    _RWIndirectArgs[1] = _NumUpdateChunks;
    _RWIndirectArgs[2] = 1;
}

#pragma kernel CullObjectToUpdateChunk

StructuredBuffer<int> _UpdateChunkList;
StructuredBuffer<int> _ClipmapCullingResult;
RWStructuredBuffer<int> _RWUpdateChunkObjectCounter;

// 2D array as 1D, single row represent an update chunk
RWStructuredBuffer<int> _RWUpdateChunkCullingResult;

[numthreads(8, 1, 1)]
void CullObjectToUpdateChunk(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    int groupThreadIndex = groupThreadId.x;
    int objectIndex = threadId.x;
    int chunkIndex = threadId.y;

    // clamp the index, mark invalid thread
    int numObjectsInClipmap = _ClipmapObjectCounter[0];
    gs_ThreadValidMask[groupThreadIndex] = objectIndex < numObjectsInClipmap;
    objectIndex = min(objectIndex, numObjectsInClipmap - 1);

    // calc update chunk's bound
    int3 chunkNumXYZ = _CascadeResolution.xyz / _UpdateChunkResolution.xyz;
    int chunkId_1D = _UpdateChunkList[chunkIndex];
    float3 chunkId_3D = Index1DTo3D(chunkId_1D, chunkNumXYZ);
    float3 chunkCenter = CalcVoxelCenterPos(chunkId_3D, chunkNumXYZ, _CascadeCenter.xyz, _CascadeSize.xyz); // we see chunk as a "large" voxel
    float3 chunkSize = _CascadeSize.xyz * _UpdateChunkResolution.xyz / _CascadeResolution.xyz;

    // 1. do culling
    int objectId = _ClipmapCullingResult[objectIndex];
    ObjectInfo objectInfo = _ObjectsInfo[objectId];
    gs_ThreadCullingResult[groupThreadIndex] = ObjectIntersectAABB(objectInfo, chunkCenter, chunkSize);

    GroupMemoryBarrierWithGroupSync();

    // 2. allocate space in culling result array
    if (groupThreadIndex == 0)
    {
        int visibleObjectCounter = 0;
        for (int i = 0; i < 8; i++)
        {
            if (IsObjectPassCulling(i))
            {
                visibleObjectCounter += 1;
            }
        }

        int startIndex = 0;
        InterlockedAdd(_RWUpdateChunkObjectCounter[chunkIndex], visibleObjectCounter, startIndex);

        for (int j = 0; j < 8; j++)
        {
            if (IsObjectPassCulling(j))
            {
                gs_ThreadWriteIndex[j] = startIndex;
                startIndex += 1;
            }
        }
    }

    GroupMemoryBarrierWithGroupSync();

    // 3. write into culling result
    int cullingResultOffset = chunkIndex * _MaxObjectNumPerUpdateChunk; // store 2d logic data to 1d buffer
    int writeIndex = gs_ThreadWriteIndex[groupThreadIndex];
    writeIndex += cullingResultOffset;
    if (IsObjectPassCulling(groupThreadIndex))
    {
        _RWUpdateChunkCullingResult[writeIndex] = objectInfo.objectId;
    }
}