#include "../RayTracing/VoxelRayTracing.hlsl"
#pragma kernel VisualizeClipmap

float4 _ScreenResolution;
float4 _CameraPosition;
float4x4 _InvViewProjMat;

int _VisualizeMode;
int _CascadeCount;
int3 _VoxelPagePoolSize;
int _SurfaceCacheAtlasResolution;
float4 _CascadeCenterArray[MAX_CASCADE_COUNT];
float4 _CascadeSizeArray[MAX_CASCADE_COUNT];
float4 _CascadeResolutionArray[MAX_CASCADE_COUNT];
float4 _CascadeMoveOffsetArray[MAX_CASCADE_COUNT];

Texture3D<uint2> _BitOccupyClipmap;
Texture3D<int> _VoxelPageClipmap;
Texture3D<float4> _VoxelPagePool;
Texture2D<float> _SceneDepthTexture;
Texture2D<float4> _SurfaceCacheAtlasToVisualize;
Texture3D<int> _VoxelOccupy;

RWTexture2D<float4> _RWSceneColorTexture;

SamplerState sampler_LinearClamp;

float3 ReconstructWorldPositionFromDepth(float2 uv, float depth)
{
    float2 ndcPosition = float2((uv.x - 0.5f) * 2.0f, (uv.y - 0.5f) * 2.0f);
    float realDepth = depth;
    float4 worldPosition = mul(_InvViewProjMat, float4(ndcPosition * realDepth, realDepth, 1.0f));
    return worldPosition.xyz / worldPosition.w;

    return worldPosition;
}

[numthreads(8, 8, 1)]
void VisualizeClipmap(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    uint2 pixelCoord = threadId.xy;
    if (pixelCoord.x >= _ScreenResolution.x || pixelCoord.y >= _ScreenResolution.y)
    {
        return;
    }

    float2 uv = (float2(pixelCoord) + 0.5) / _ScreenResolution.xy;
    float rawDepth = _SceneDepthTexture.Load(int3(pixelCoord, 0)).r;
    float pixelDepth = (1.0 - rawDepth) * 2.0 - 1.0;
    float3 pixelWorldPosition = ReconstructWorldPositionFromDepth(uv, pixelDepth);
    
    float3 rayDir = normalize(pixelWorldPosition - _CameraPosition.xyz);
    float3 color = float3(0, 0, 0) + _VoxelOccupy[uint3(0, 0, 0)]; // used to debug, make sure it's (0, 0, 0)

    ClipmapInfo clipmapInfo;
    clipmapInfo.cascadeCount = _CascadeCount;
    clipmapInfo.cascadeCenterArray = _CascadeCenterArray;
    clipmapInfo.cascadeSizeArray = _CascadeSizeArray;
    clipmapInfo.cascadeResolutionArray = _CascadeResolutionArray;
    clipmapInfo.cascadeMoveOffsetArray = _CascadeMoveOffsetArray;
    
    VoxelRayTracingHitPayload hit = VoxelRaytracing(clipmapInfo, _BitOccupyClipmap, _CameraPosition, rayDir);
    
    if (hit.isHit)
    {
#if USE_DEBUG_COLOR
        color += hit.debugColor;
#else
        int voxelPageId = _VoxelPageClipmap.Load(uint4(hit.clipmapAccessIndex, 0)).r;
        int3 indexInPool = PageAddressMapping(voxelPageId, _VoxelPagePoolSize, hit.voxelIndex);
        float4 rawPageData = _VoxelPagePool.Load(uint4(indexInPool, 0));
        VoxelPageData pageData = DecodeVoxelPage(rawPageData);

        ObjectInfo objectInfo = _ObjectsInfo[pageData.objectId];
        float3 surfaceCacheColor = SurfaceCacheSampleColor(
            _SurfaceCacheAtlasToVisualize, sampler_LinearClamp,
            pageData.uvInAtlas, _SurfaceCacheAtlasResolution, pageData.bilinearValidMask
        );

        if (_VisualizeMode == 1)  // is normal
        {
            float3 localSpaceNormal = surfaceCacheColor.xyz * 2 - 1;
            float3 worldNormal = normalize(mul(float4(localSpaceNormal, 0), objectInfo.localToWorldMatrix).xyz);
            color += worldNormal * 0.5 + 0.5;
        }
        else // other
        {
            color += surfaceCacheColor;
        }
#endif
    }

    _RWSceneColorTexture[pixelCoord] = float4(color, 1);
}