#include "../VoxelLighting/VoxelLightingParameters.hlsl"
#pragma kernel VisualizeClipmap

#pragma multi_compile _ USE_DISTANCE_FIELD

float4 _ScreenResolution;
float4 _CameraPosition;
float4x4 _InvViewProjMat;
float4 _ZBufferParam;
float4x4 _InvProjMat;
float4x4 _InvViewMat;

int _VisualizeMode;
int _VisualizeCascadeLevel;
int _VisualizeUpdateChunk;

Texture2D<float> _SceneDepthTexture;
RWTexture2D<float4> _RWSceneColorTexture;

Texture3D<float> _VoxelOccupy;

int _UpdateChunkCount;
float3 _UpdateChunkResolution;
StructuredBuffer<int> _UpdateChunkList;

float3 ReconstructWorldPositionFromDepth(float2 uv, float depth)
{
    float reverseDepth = 1 - depth;
    float eyeDepth = 1.0 / (_ZBufferParam.z * reverseDepth + _ZBufferParam.w);
    float4 clipPos = float4(uv * 2.0 - 1.0, reverseDepth * 2.0 - 1.0, 1.0);
    float4 viewPos = mul(_InvProjMat, clipPos);
    viewPos /= viewPos.w;
    
    float4 worldPos = mul(_InvViewMat, viewPos);
    
    return worldPos.xyz;
}

[numthreads(8, 8, 1)]
void VisualizeClipmap(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    uint2 pixelCoord = threadId.xy;
    if (pixelCoord.x >= _ScreenResolution.x || pixelCoord.y >= _ScreenResolution.y)
    {
        return;
    }

    float2 uv = (float2(pixelCoord) + 0.5) / _ScreenResolution.xy;
    float rawDepth = _SceneDepthTexture.Load(int3(pixelCoord, 0)).r;
    float3 pixelWorldPosition = ReconstructWorldPositionFromDepth(uv, rawDepth);
    
    ClipmapInfo clipmapInfo = ResolveClipmapInfo();
    
    float3 rayDir = normalize(pixelWorldPosition - _CameraPosition.xyz);
    float3 rayEnd = rayDir * 1000;
    float3 color = float3(0, 0, 0) + _VoxelOccupy[uint3(0, 0, 0)];
    
    VoxelRaytracingRequest RTRequest = (VoxelRaytracingRequest) 0;
    RTRequest.rayStart = _CameraPosition;
    RTRequest.rayDir = rayDir;
    RTRequest.minCascadeIndex = clamp(_VisualizeCascadeLevel, 0, _CascadeCount - 1);
    RTRequest.maxCascadeIndex = _CascadeCount - 1;
    RTRequest.maxStepNum = 1000;
    RTRequest.maxDistance = 100000;
    
#if USE_ROMA
    VoxelRayTracingHitPayload hit = OccupancyMapRaytracing(clipmapInfo, _DistanceFieldClipmap, sampler_linearClamp, RTRequest);
#elif USE_DISTANCE_FIELD
    VoxelRayTracingHitPayload hit = DistanceFieldRaytracing(clipmapInfo, _DistanceFieldClipmap, sampler_linearClamp, RTRequest);
#else
    VoxelRayTracingHitPayload hit = VoxelRaytracing(clipmapInfo, _VoxelBitOccupyClipmap, RTRequest);
#endif
    
    if (hit.isHit)
    {
        // print hit distance
    #if 0
        _RWSceneColorTexture[pixelCoord] = float4(
            length(hit.position - _CameraPosition) / 1000.0f,
            0, 0, 1
        );
        return;
    #endif
        
        float3 debugColor = float3(0, 0, 0);
        int voxelPageId = _VoxelPageClipmap.Load(uint4(hit.clipmapAccessIndex, 0)).r;
        
        if (voxelPageId != PAGE_ID_INVALID)
        {
            int3 indexInPool = PageAddressMapping(voxelPageId, _VoxelPageCountInXYZ, hit.voxelIndex);
            
            if (_VisualizeMode == 1)  // base color
            {
                debugColor = _VoxelPoolBaseColor.Load(uint4(indexInPool, 0)).rgb;
            }
            if (_VisualizeMode == 2)  // normal
            {
                debugColor = _VoxelPoolNormal.Load(uint4(indexInPool, 0)).rgb;
            }
            if (_VisualizeMode == 3)  // emissive
            {
                debugColor = _VoxelPoolEmissive.Load(uint4(indexInPool, 0)).rgb;
            }
            if (_VisualizeMode == 4)  // radiance
            {
                float3 worldNormal = _VoxelPoolNormal.Load(uint4(indexInPool, 0)).rgb * 2 - 1;
                int isBackFace = dot(worldNormal, -rayDir) < 0;
                int3 twoSideIndex = TwoSideAddressMapping(indexInPool, isBackFace);
                debugColor = _VoxelPoolRadiance.Load(uint4(twoSideIndex, 0)).rgb;
            }
            if (_VisualizeMode == 5)
            {
                switch (hit.cascadeIndex)
                {
                    case 0:
                        debugColor = float3(0.2, 0.6, 0.4);
                        break;
                    case 1:
                        debugColor = float3(0.4, 0.3, 0.7);
                        break;
                    case 2:
                        debugColor = float3(0.7, 0.9, 0.2);
                        break;
                    case 3:
                        debugColor = float3(0.1, 0.8, 0.5);
                        break;
                    default:
                        break;
                }
            }
        }
        // for invalid page maybe runout of space, we just give it a warning color
        else
        {
            debugColor = float3(1, 0, 1);
        }
        
        color += debugColor;
    }
    
    if (_VisualizeUpdateChunk > 0)
    {
        //int cascadeIndex = _VisualizeUpdateChunk - 1;
        //for (int i = 0; i < _UpdateChunkCount; i++)
        //{
        //    int3 chunkNumXYZ = _CascadeResolution / _UpdateChunkResolution;
        //    int chunkId_1D = _UpdateChunkList[i];
        //    float3 chunkId_3D = Index1DTo3D(chunkId_1D, chunkNumXYZ);
        //    float3 chunkCenter = CalcVoxelCenterPos(chunkId_3D, chunkNumXYZ, _CascadeCenterArray[cascadeIndex], _CascadeSizeArray[cascadeIndex]);
        //    float3 chunkCoverRange = _CascadeSizeArray[cascadeIndex] * _UpdateChunkResolution / _CascadeResolution;

        //    float3 boxMin = chunkCenter - chunkCoverRange * 0.5;
        //    float3 boxMax = chunkCenter + chunkCoverRange * 0.5;
        //    float2 hitChunkT = LineBoxIntersect(_CameraPosition, rayEnd, boxMin, boxMax);
        //    if (hitChunkT.x < hitChunkT.y)
        //    {
        //        color += float3(0, 0.5, 0.8);
        //    }
        //}
    }

    _RWSceneColorTexture[pixelCoord] = float4(color, 1);
}