#include "../../GICommon.hlsl"
#pragma kernel VoxelPageInit

RWTexture3D<uint2> _RWVoxelMap;
RWTexture3D<int> _RWVoxelPageClipmap;
RWTexture3D<float4> _RWVoxelPagePool;

[numthreads(4, 4, 4)]
void VoxelPageInit(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    _RWVoxelMap[threadId] = uint2(0, 0);
    _RWVoxelPageClipmap[threadId] = PAGE_ID_INVALID;
    
    for (int i = 0; i < 4; i++)
    {
        for (int j = 0; j < 4; j++)
        {
            _RWVoxelPagePool[uint3(threadId.x * 4 + i, threadId.y * 4 + j, threadId.z)] = float4(0, 0, 0, 0);
        }
    }
}