#include "../../GICommon.hlsl"
#pragma kernel VoxelInject

cbuffer _Params
{
    float4 _CascadeCenter;
    float4 _CascadeSize;
    float4 _CascadeResolution;
    float4 _UpdateChunkResolution;
    int _NumObjects;
    int _NumUpdateChunks;
    int _NumThreadsForCulling;
    int _MaxObjectNumPerUpdateChunk;
};

int _SurfaceCacheAtlasResolution;
int _CascadeIndex;
int3 _CascadeMoveOffset;
int3 _VoxelPagePoolSize;

StructuredBuffer<int> _UpdateChunkList;
StructuredBuffer<int> _UpdateChunkCullingResult;
StructuredBuffer<int> _UpdateChunkObjectCounter;
StructuredBuffer<CardInfo> _CardInfoBuffer;

Texture2D _SurfaceCacheAtlasDepth;
SamplerState sampler_LinearClamp;

RWTexture3D<uint2> _RWVoxelBitOccupyClipmap;
RWTexture3D<uint> _RWVoxelOccupy;

RWTexture3D<int> _RWVoxelPageClipmap;
RWStructuredBuffer<int> _RWVoxelPageAllocator;
RWStructuredBuffer<int> _RWVoxelPageFreeList;
RWStructuredBuffer<int> _RWVoxelPageReleaseList;
RWTexture3D<float4> _RWVoxelPagePool;

groupshared bool gs_ThreadVoxelOccupy[64];
groupshared int gs_VoxelPageId;

[numthreads(4, 4, 4)]
void VoxelInject(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    int3 chunkNumXYZ = _CascadeResolution / _UpdateChunkResolution;
    int chunkIndex = threadId.x / _UpdateChunkResolution.x;
    int chunkId_1D = _UpdateChunkList[chunkIndex];
    int3 chunkId_3D = Index1DTo3D(chunkId_1D, chunkNumXYZ);

    int3 voxelIndexInChunk = int3(threadId.x % _UpdateChunkResolution.x, threadId.y, threadId.z); // [0 ~ UpdateChunkResolution-1]
    int3 voxelIndex = chunkId_3D * _UpdateChunkResolution + voxelIndexInChunk; // [0 ~ CascadeResolution]
    float3 voxelPosition = CalcVoxelCenterPos(voxelIndex, _CascadeResolution, _CascadeCenter, _CascadeSize);
    float voxelCellSize = _CascadeSize / _CascadeResolution.xyz;
    int voxelId1D = Index3DTo1D(voxelIndexInChunk, uint3(16, 16, 16));

    int cullingResultOffset = chunkIndex * _MaxObjectNumPerUpdateChunk; // access 2d logic data in 1d buffer
    int numObjectsInUpdateChunk = _UpdateChunkObjectCounter[chunkIndex];

    bool hasVoxel = false;
    VoxelPageData voxelPageData = GetEmptyPageData();

    // 1. loop all objects in update chunk, see if clipmap's voxel intersect with per object voxel
    for (int i = 0; i < numObjectsInUpdateChunk; i++)
    {
        int objectId = _UpdateChunkCullingResult[cullingResultOffset + i];
        ObjectInfo objectInfo = _ObjectsInfo[objectId];

        // transform voxel center to object's space
        //float3 localPosition = mul(float4(voxelPosition, 1), objectInfo.worldToLocalMatrix);
        float3 localPosition = mul(objectInfo.worldToLocalMatrix, float4(voxelPosition, 1));

        // note: ObjectInfo.WorldBoundsMax will extend when rotate object
        // we just want get LocalBound's size in world space
        float3 objectWorldScale = float3(
            length(objectInfo.localToWorldMatrix[0].xyz),
            length(objectInfo.localToWorldMatrix[1].xyz),
            length(objectInfo.localToWorldMatrix[2].xyz)
        );
        float3 objectLocalBoundSize = objectInfo.localBoundsMax - objectInfo.localBoundsMin;
        float3 objectWorldBound = objectLocalBoundSize * objectWorldScale;
        float objectWorldBoundSize = max(max(objectWorldBound.x, objectWorldBound.y), objectWorldBound.z); // @TODO: select xyz component for different card orientation

        int cardCount = objectInfo.cardCount;
        int cardResolution = objectInfo.resolution;
        int cardOffset = objectId * MAX_CARD_PER_MESH;

        for (int cardIndex = 0; cardIndex < cardCount; cardIndex++)
        {
            CardInfo cardInfo = _CardInfoBuffer[cardOffset + cardIndex];
            float4x4 localToCard = cardInfo.localToCardMatrix;
            
            // 1.2.1. transform voxel pos to card capture's uv space (like shadowmap)
            float3 cardUVZ = mul(localToCard, float4(localPosition, 1));
            cardUVZ.xy = saturate(cardUVZ.xy * 0.5 + 0.5);
            
            // 1.2.2. map card capture uv to atlas uv
            float4 cardSizeAndOffset = cardInfo.cardUVTransform;
            float4 UVTransform = cardSizeAndOffset / float(_SurfaceCacheAtlasResolution);
            cardUVZ.xy = cardUVZ.xy * UVTransform.xy + UVTransform.zw;
            cardUVZ.y = 1.0 - cardUVZ.y;

            // 1.2.3. sample mesh card depth atlas, do "height field" intersection
            float4 outBilinearValidMask = float4(0, 0, 0, 0);
            float cardDepth = SurfaceCacheSampleDepth(_SurfaceCacheAtlasDepth, sampler_LinearClamp, cardUVZ.xy, _SurfaceCacheAtlasResolution, outBilinearValidMask);
            float voxelDepth = (cardUVZ.z * 0.5f) + 0.5f;

            if (cardDepth == 0)
            {
                continue;
            }

            float worldDistancce = abs(cardDepth - voxelDepth) * objectWorldBoundSize;
            if (worldDistancce < voxelCellSize * 0.5)  // tolerance radius is sqrt(2) / 2, for unit cube
            {
                hasVoxel = true;
                voxelPageData.uvInAtlas = cardUVZ.xy;
                voxelPageData.objectId = objectId;
                voxelPageData.cardId = cardIndex;
                voxelPageData.bilinearValidMask = outBilinearValidMask;
                _RWVoxelOccupy[voxelIndex + uint3(0, 0, 128 * _CascadeIndex)] = 1;
                break;
            }
        }
        
        if (hasVoxel)
            break;
    }

    // 2. restore result into temp LDS
    int threadIndex = Index3DTo1D_4x4x4(groupThreadId);
    gs_ThreadVoxelOccupy[threadIndex] = hasVoxel;

    GroupMemoryBarrierWithGroupSync();

    // 3. single head thread encode ThreadVoxelOccupy to uint64, write into bit occupy volume
    uint2 bitOccupyBlock = uint2(0, 0);
    int3 blockAccessIndex = ClipmapAddressMapping(voxelIndex, _CascadeResolution, _CascadeMoveOffset, _CascadeIndex);
    if (threadIndex == 0)
    {
        for (int i = 0; i < 64; i++)
        {
            SetUint64SingleBit(bitOccupyBlock, i, gs_ThreadVoxelOccupy[i]);
        }
        
        _RWVoxelBitOccupyClipmap[blockAccessIndex] = bitOccupyBlock;
    }

    // 4. single head thread allocate or release page
    if (threadIndex == 0)
    {
        bool blockHasVoxel = any(bitOccupyBlock > 0);
        int pageId = _RWVoxelPageClipmap[blockAccessIndex];

        // 4.1. current block has voxel but not allocate voxel page, we just allocate for it
        if (pageId == PAGE_ID_INVALID && blockHasVoxel)
        {
            int freePointer = 0;
            InterlockedAdd(_RWVoxelPageAllocator[FREE_PAGE_POINTER], 1, freePointer);
            pageId = _RWVoxelPageFreeList[freePointer];
            _RWVoxelPageFreeList[freePointer] = PAGE_ID_INVALID;
        }
        // 4.2. current block is empty but hold a voxel page, we just release it
        else if (pageId != PAGE_ID_INVALID && !blockHasVoxel)
        {
            int releasePointer = 0;
            InterlockedAdd(_RWVoxelPageAllocator[RELEASE_PAGE_POINTER], 1, releasePointer);
            _RWVoxelPageReleaseList[releasePointer] = pageId;
            pageId = PAGE_ID_INVALID;
        }
        
        // 4.3. anyway we get a valid page id, boardcast it to all voxel in same voxel block (same thread group)
        gs_VoxelPageId = pageId;
        _RWVoxelPageClipmap[blockAccessIndex] = pageId;
    }
    
    GroupMemoryBarrierWithGroupSync();

    // 5. every voxel write it's intersect result into voxel pool
    if (gs_VoxelPageId != PAGE_ID_INVALID)
    {
        int3 writeIndex = PageAddressMapping(gs_VoxelPageId, _VoxelPagePoolSize, voxelIndex);
        _RWVoxelPagePool[writeIndex] = EncodeVoxelPage(voxelPageData);
    }
}