#include "../../GICommon.hlsl"
#pragma kernel VoxelInject

#pragma multi_compile _ USE_DISTANCE_FIELD
//#pragma multi_compile _ USE_ROMA

cbuffer _Params
{
    float4 _CascadeCenter;
    float4 _CascadeSize;
    float4 _CascadeResolution;
    float4 _UpdateChunkResolution;
    int _NumObjects;
    int _NumUpdateChunks;
    int _NumThreadsForCulling;
    int _MaxObjectNumPerUpdateChunk;
    float _RejectFactor;
    float _VoxelCellSize;
};

int _SurfaceCacheAtlasResolution;
int _CascadeIndex;
int3 _CascadeScrolling;
int3 _VoxelPageCountInXYZ;

StructuredBuffer<int> _UpdateChunkList;
StructuredBuffer<int> _UpdateChunkCullingResult;
StructuredBuffer<int> _UpdateChunkObjectCounter;
StructuredBuffer<SurfaceCacheInfo> _SurfaceCacheInfoBuffer;
StructuredBuffer<CardInfo> _CardInfoBuffer;

Texture2D _SurfaceCacheAtlasBaseColor;
Texture2D _SurfaceCacheAtlasNormal;
Texture2D _SurfaceCacheAtlasEmissive;
Texture2D _SurfaceCacheAtlasDepth;
SamplerState sampler_LinearClamp;

RWTexture3D<uint2> _RWVoxelBitOccupyClipmap;
//RWTexture3D<float> _RWVoxelOccupy;

RWTexture3D<int> _RWVoxelPageClipmap;
RWStructuredBuffer<int> _RWVoxelPageFreeList;
RWStructuredBuffer<int> _RWVoxelPageReleaseList;
RWTexture3D<float3> _RWVoxelPoolBaseColor;
RWTexture3D<float3> _RWVoxelPoolNormal;
RWTexture3D<float3> _RWVoxelPoolEmissive;

RWTexture2DArray<uint> _RWScrollingBOM;
RWTexture3D<float> _RWDistanceFieldClipmap;

groupshared bool gs_ThreadVoxelOccupy[64];
groupshared int gs_VoxelPageId;

// https://iquilezles.org/articles/distfunctions/
float DFBox(float3 localSpacePosition, float3 objectLocalBoundSize)
{
    float3 q = abs(localSpacePosition) - objectLocalBoundSize * 0.5;
    return length(max(q, 0.0)) + min(max(q.x, max(q.y, q.z)), 0.0);
}

[numthreads(4, 4, 4)]
void VoxelInject(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    int3 chunkNumXYZ = _CascadeResolution / _UpdateChunkResolution;
    int chunkIndex = threadId.x / _UpdateChunkResolution.x;
    int chunkId_1D = _UpdateChunkList[chunkIndex];
    int3 chunkId_3D = Index1DTo3D(chunkId_1D, chunkNumXYZ);

    int3 voxelIndexInChunk = int3(threadId.x % _UpdateChunkResolution.x, threadId.y, threadId.z); // [0 ~ UpdateChunkResolution-1]
    int3 voxelIndex = chunkId_3D * _UpdateChunkResolution + voxelIndexInChunk; // [0 ~ CascadeResolution]
    float3 voxelPosition = CalcVoxelCenterPos(voxelIndex, _CascadeResolution, _CascadeCenter, _CascadeSize);
    float voxelCellSize = _CascadeSize / _CascadeResolution.xyz;

    int cullingResultStart = chunkIndex * _MaxObjectNumPerUpdateChunk; // access 2d logic data in 1d buffer
    int numObjectsInUpdateChunk = min(_UpdateChunkObjectCounter[chunkIndex], _MaxObjectNumPerUpdateChunk);

    // if hit voxel, we record hit point's info in this var
    bool hasVoxel = false;
    float2 uvInAtlas = (float2) 0;
    float4x4 localToWorldMatrix = (float4x4) 0; // for transform hit normal to world
    float4 bilinearValidMask = (float4) 0;      // valid pixel mask when doing bilinear filter in surface cache atlas
    float minDistance = 1000;                 // min distance from cur voxel to object surface

    // 1. loop all objects in update chunk, see if clipmap's voxel intersect with object
    for (int i = 0; i < numObjectsInUpdateChunk; i++)
    {
        int objectId = _UpdateChunkCullingResult[cullingResultStart + i];
        ObjectInfo objectInfo = _ObjectsInfo[objectId];

        // transform voxel center to object's space
        float3 localPosition = mul(objectInfo.worldToLocalMatrix, float4(voxelPosition, 1));

        // note: ObjectInfo.WorldBoundsMax will extend when rotate object
        // we just want get LocalBound's size in world space
        float3 objectWorldScale = float3(
            length(objectInfo.localToWorldMatrix[0].xyz),
            length(objectInfo.localToWorldMatrix[1].xyz),
            length(objectInfo.localToWorldMatrix[2].xyz)
        );
        float3 objectLocalBoundSize = objectInfo.localBoundsMax - objectInfo.localBoundsMin;
        float3 objectWorldBound = objectLocalBoundSize * objectWorldScale; 
        // note: must sync with projection matrix in CalcCardCaptureViewProjectionMatrix in c#
        float orthoDepthLocalSize = max(max(objectLocalBoundSize.x, objectLocalBoundSize.y), objectLocalBoundSize.z);
        float orthoDepthWorldSize = max(max(objectWorldBound.x, objectWorldBound.y), objectWorldBound.z); 
        
        // if voxel is too far from object we reject
        float3 localCellSize = voxelCellSize.xxx / objectWorldScale;
        float localSpaceCellRadius = max(max(localCellSize.x, localCellSize.y), localCellSize.z) * 1.414; // sqrt(2) for diagonal
        float3 toleranceBoundMin = objectInfo.localBoundsMin - localSpaceCellRadius.xxx;
        float3 toleranceBoundMax = objectInfo.localBoundsMax + localSpaceCellRadius.xxx;
        if (any(localPosition < toleranceBoundMin) || any(localPosition > toleranceBoundMax))
        {
            // calculate approximate distance to boost distance field coverage
#if USE_DISTANCE_FIELD
            float distanceToObjectApprox = DFBox(localPosition, objectLocalBoundSize) * max(max(objectWorldScale.x, objectWorldScale.y), objectWorldScale.z);
            distanceToObjectApprox = max(distanceToObjectApprox, voxelCellSize * 2); // prevent distance too small to block the ray
            minDistance = min(minDistance, distanceToObjectApprox);
#endif
            continue;
        }
        
        int surfaceCacheId = objectInfo.surfaceCacheId;
        SurfaceCacheInfo surfaceCacheInfo = _SurfaceCacheInfoBuffer[surfaceCacheId];
        int cardCount = surfaceCacheInfo.meshCardCount;
        int cardResolution = surfaceCacheInfo.meshCardResolution;
        int cardOffset = surfaceCacheId * MAX_CARD_PER_MESH;

        for (int cardIndex = 0; cardIndex < cardCount; cardIndex++)
        {
            CardInfo cardInfo = _CardInfoBuffer[cardOffset + cardIndex];
            float4x4 localToCard = cardInfo.localToCardMatrix;
            
            // 1.2.1. transform voxel pos to card capture's uv space (like shadowmap)
            float3 cardUVZ = mul(localToCard, float4(localPosition, 1));
            cardUVZ.xy = saturate(cardUVZ.xy * 0.5 + 0.5);
            
            // 1.2.2. map card capture uv to atlas uv
            float4 cardSizeAndOffset = cardInfo.cardUVTransform;
            float4 UVTransform = cardSizeAndOffset / float(_SurfaceCacheAtlasResolution);
            cardUVZ.xy = cardUVZ.xy * UVTransform.xy + UVTransform.zw;
            cardUVZ.y = 1.0 - cardUVZ.y;
            uvInAtlas = cardUVZ.xy;

            // 1.2.3. sample mesh card depth atlas, do "height field" intersection
            float cardDepth = SurfaceCacheSampleDepth(_SurfaceCacheAtlasDepth, sampler_LinearClamp, uvInAtlas, _SurfaceCacheAtlasResolution, bilinearValidMask);
            float voxelDepth = (cardUVZ.z * 0.5f) + 0.5f;

            if (cardDepth == 0 || voxelDepth < 0 || voxelDepth > 1)
            {
                continue;
            }

            //float worldDistance = abs(cardDepth - voxelDepth) * orthoDepthWorldSize;
            //if (worldDistance < voxelCellSize * 0.707)  // tolerance radius is sqrt(2) / 2, for unit cube
            float localDistance = abs(cardDepth - voxelDepth) * orthoDepthLocalSize;
            float worldDistance = abs(cardDepth - voxelDepth) * orthoDepthWorldSize;
            
#if USE_DISTANCE_FIELD
            minDistance = min(minDistance, worldDistance);
#endif
            //if (worldDistance < voxelCellSize * 0.707)
            if (localDistance < localSpaceCellRadius * 0.5)
            {
                hasVoxel = true;
                localToWorldMatrix = objectInfo.localToWorldMatrix;
                break;
            }
        }
        
        if (hasVoxel)
            break;
    }

    // 2. restore result into temp LDS
    int threadIndex = Index3DTo1D_4x4x4(groupThreadId);
    gs_ThreadVoxelOccupy[threadIndex] = hasVoxel;

    GroupMemoryBarrierWithGroupSync();
                
    uint3 scrollingIndex = (voxelIndex + _CascadeScrolling) % (int3) _CascadeResolution;
    int arrayIndex = scrollingIndex.z / 16;
    int bitIndex = scrollingIndex.z % 16;
    
    if (hasVoxel)
    {
        uint bitMask = 1u << (15 - bitIndex);
        InterlockedOr(_RWScrollingBOM[uint3(scrollingIndex.xy, arrayIndex + _CascadeIndex * BASE_OM_SIZE / 16)], bitMask);
    }
    else
    {
        uint bitMask = ~(1u << (15 - bitIndex));
        InterlockedAnd(_RWScrollingBOM[uint3(scrollingIndex.xy, arrayIndex + _CascadeIndex * BASE_OM_SIZE / 16)], bitMask);
    }
    //_RWVoxelOccupy[scrollingIndex + uint3(0, 0, (int) _CascadeResolution.x * _CascadeIndex)] = hasVoxel ? 1.0f : 0.0f;

    // 3. single head thread encode ThreadVoxelOccupy to uint64, write into bit occupy volume
    uint2 bitOccupyBlock = uint2(0, 0);
    int3 blockIndex = voxelIndex / VOXEL_BLOCK_SIZE;
    int3 blockAccessIndex = BlockClipmapAddressMapping(blockIndex, _CascadeResolution, _CascadeScrolling, _CascadeIndex);
    if (threadIndex == 0)
    {
        for (int i = 0; i < 64; i++)
        {
            SetUint64SingleBit(bitOccupyBlock, i, gs_ThreadVoxelOccupy[i]);
        }
        
        _RWVoxelBitOccupyClipmap[blockAccessIndex] = bitOccupyBlock;
    }

    // 4. single head thread allocate or release page
    if (threadIndex == 0)
    {
        bool blockHasVoxel = any(bitOccupyBlock > 0);
        int pageId = _RWVoxelPageClipmap[blockAccessIndex];
        int maxPageNum = _VoxelPageCountInXYZ.x * _VoxelPageCountInXYZ.y * _VoxelPageCountInXYZ.z;
        int pointerIndex = maxPageNum; // we use last element as allocator pointer

        // 4.1. current block has voxel but not allocate voxel page, we just allocate for it
        if (pageId == PAGE_ID_INVALID && blockHasVoxel)
        {
            int freePointer = 0;
            InterlockedAdd(_RWVoxelPageFreeList[pointerIndex], 1, freePointer);
            
            // check if free pointer is valid
            if (freePointer < maxPageNum)
            {
                pageId = _RWVoxelPageFreeList[freePointer];
                _RWVoxelPageFreeList[freePointer] = PAGE_ID_INVALID;
            }
        }
        // 4.2. current block is empty but hold a voxel page, we just release it
        else if (pageId != PAGE_ID_INVALID && !blockHasVoxel)
        {
            int releasePointer = 0;
            InterlockedAdd(_RWVoxelPageReleaseList[pointerIndex], 1, releasePointer);
            _RWVoxelPageReleaseList[releasePointer] = pageId;
            pageId = PAGE_ID_INVALID;
        }
        
        // 4.3. anyway we get a page id, boardcast it to all voxel in same voxel block (same thread group)
        gs_VoxelPageId = pageId;
        _RWVoxelPageClipmap[blockAccessIndex] = pageId;
    }
    
    GroupMemoryBarrierWithGroupSync();

    // 5. every voxel write it's intersect result into voxel pool
    if (gs_VoxelPageId != PAGE_ID_INVALID && hasVoxel)
    {
        float3 baseColor = SurfaceCacheSampleColor(_SurfaceCacheAtlasBaseColor, sampler_LinearClamp, uvInAtlas, _SurfaceCacheAtlasResolution, bilinearValidMask);
        float3 emissive = SurfaceCacheSampleColor(_SurfaceCacheAtlasEmissive, sampler_LinearClamp, uvInAtlas, _SurfaceCacheAtlasResolution, bilinearValidMask);
        float3 localSpaceNormal = SurfaceCacheSampleColor(_SurfaceCacheAtlasNormal, sampler_LinearClamp, uvInAtlas, _SurfaceCacheAtlasResolution, bilinearValidMask) * 2 - 1;
        //float3 worldNormal = normalize(mul(float4(localSpaceNormal, 0), localToWorldMatrix).xyz) * 0.5 + 0.5;
        float3 worldNormal = normalize(mul(localToWorldMatrix, float4(localSpaceNormal, 0)).xyz) * 0.5 + 0.5;

        int3 writeIndex = PageAddressMapping(gs_VoxelPageId, _VoxelPageCountInXYZ, voxelIndex);
        _RWVoxelPoolBaseColor[writeIndex] = baseColor;
        _RWVoxelPoolNormal[writeIndex] = worldNormal;
        _RWVoxelPoolEmissive[writeIndex] = emissive;
    }
    
    // 6. write to distance field
#if USE_DISTANCE_FIELD
    int3 voxelWriteIndex = blockAccessIndex * VOXEL_BLOCK_SIZE + voxelIndex % VOXEL_BLOCK_SIZE;
    _RWDistanceFieldClipmap[voxelWriteIndex] = hasVoxel ? 0 : EncodeDistance(minDistance, voxelCellSize);
#endif
}

// --------------------------------------------------------------------------------------- //
#pragma kernel DistanceFieldPropagate

Texture3D<float> _DistanceFieldClipmap;

[numthreads(4, 4, 4)]
void DistanceFieldPropagate(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    int3 clipmapOffset = int3(0, 0, _CascadeIndex * _CascadeResolution.z);
    int3 readWriteIndex = threadId + clipmapOffset;

    int3 voxelIndex = (threadId + _CascadeScrolling) % _CascadeResolution;
    float voxelSize = _CascadeSize.x / float(_CascadeResolution.z);

    // 1. clamp sample to logic boundary
    int3 offsets[6] = { int3(-1, 0, 0), int3(1, 0, 0), int3(0, -1, 0), int3(0, 1, 0), int3(0, 0, -1), int3(0, 0, 1) };
    for (int i = 0; i < 6; i++)
    {
        int3 offsetIndex = voxelIndex + offsets[i];
        if (any(offsetIndex < 0) || any(offsetIndex >= _CascadeResolution))
        {
            offsets[i] = int3(0, 0, 0);
        }
    }

    // 2. sample neighbor cell's distance
    float distance = DecodeDistance(_DistanceFieldClipmap[readWriteIndex], voxelSize);
    for (int i = 0; i < 6; i++)
    {
        // clamp sample wrap physical boundary
        int3 offsetIndex = (threadId + offsets[i]) % _CascadeResolution;
        offsetIndex += (offsetIndex < int3(0, 0, 0)) * _CascadeResolution;
        offsetIndex += clipmapOffset;
        
        float neighborVal = DecodeDistance(_DistanceFieldClipmap[offsetIndex], voxelSize);
        distance = min(distance, neighborVal + voxelSize);
    }

    // 3. write distance
    _RWDistanceFieldClipmap[readWriteIndex] = EncodeDistance(distance, voxelSize);
}

// --------------------------------------------------------------------------------------- //
#pragma kernel BaseOccupancyMapProject

Texture2DArray<uint> _ScrollingBOM;
RWTexture2DArray<uint> _RWBaseOccupancyMap;

[numthreads(4, 4, 1)]
void BaseOccupancyMapProject(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    uint2 writeIndex = threadId.xy;
    uint2 projectIndex = (threadId.xy + _CascadeScrolling.xy) % (int2) _CascadeResolution;
    uint projectChunkZ = _CascadeScrolling.z / 16;
    
    int OMClipCount = _CascadeResolution.z / 32;
    for (int i = 0; i < OMClipCount; i++)
    {
        uint readIndexZ = (i * 2 + projectChunkZ) % (OMClipCount * 2);
        uint combinedOccupy = (_ScrollingBOM[uint3(projectIndex, readIndexZ + _CascadeIndex * BASE_OM_SIZE / 16)] << 16)
                                + _ScrollingBOM[uint3(projectIndex, readIndexZ + _CascadeIndex * BASE_OM_SIZE / 16 + 1)];
        _RWBaseOccupancyMap[uint3(writeIndex, i + _CascadeIndex * BASE_OM_SIZE / 32)] = combinedOccupy;
    }
}

// --------------------------------------------------------------------------------------- //
#pragma kernel GenerateROMA

int _UpdateFrame;
int _UpdateOMPerFrame;
float4x4 _BaseOMViewProjMat;

Texture2DArray<uint> _BaseOccupancyMap;
StructuredBuffer<DirectionParams> _DirectionParamsArray;
RWTexture2DArray<uint> _RWROMA;
RWStructuredBuffer<float4> _RWROMACenter;

[numthreads(16, 16, 1)]
void GenerateROMA(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    const uint occupancyMapSize = (uint) _CascadeResolution.z;
    const uint occupancyMapClipCount = occupancyMapSize / 32;
    
    const uint2 pixelIndex = threadId.xy;
    const uint arrayIndex = _UpdateFrame * _UpdateOMPerFrame + threadId.z;
    const float4x4 invViewProjMat = _DirectionParamsArray[arrayIndex].invViewProjMat;
    
    const float2 uv = (pixelIndex + 0.5f) / occupancyMapSize;

    // Setup a bunch of samples and transform them to base om space
    const float3 startPosUV = float3(uv, 0.5f / occupancyMapSize);
    const float3 endPosUV = float3(uv, 1.0f - 0.5f / occupancyMapSize);
    const float3 startPosWS = positionUVToWS(startPosUV, invViewProjMat);
    const float3 endPosWS = positionUVToWS(endPosUV, invViewProjMat);

    float3 curPosBaseUV = positionWSToUV(startPosWS, _BaseOMViewProjMat);
    const float3 endPosBaseUV = positionWSToUV(endPosWS, _BaseOMViewProjMat);
    const float3 rayStep = (endPosBaseUV - curPosBaseUV) / (occupancyMapSize - 1.f);
    
    // Clear data for previous frame
    for (int i = 0; i < occupancyMapClipCount; i++)
    {
        for (int cascadeId = 0; cascadeId < 4; cascadeId++)
            _RWROMA[uint3(pixelIndex, occupancyMapClipCount * arrayIndex + cascadeId * BASE_OM_SIZE / 32 * ROMA_COUNT + i)] = 0;
    }

    for (int i = 0; i < occupancyMapSize; i++, curPosBaseUV += rayStep)
    {
        if (any(curPosBaseUV < 0) || any(curPosBaseUV > 1))
            continue;
        const uint3 baseVoxelIndex = floor(curPosBaseUV * occupancyMapSize);
        // Get ombits from base om, Check if the bit is occupied
        uint baseClipIndex = baseVoxelIndex.z / 32;
        uint bitBase = baseVoxelIndex.z % 32;
        
        for (int cascadeId = 0; cascadeId < 4; cascadeId++)
        {
            uint OMbits = _BaseOccupancyMap[uint3(baseVoxelIndex.xy, baseClipIndex + cascadeId * BASE_OM_SIZE / 32)];
            uint occupied = (OMbits << bitBase) >> 31;

            // Save result
            if (occupied > 0)
            {
                uint clipIndex = i / 32;
                uint remainder = i % 32;
                uint result = 1 << (31 - remainder);
                uint currentValue = _RWROMA[uint3(pixelIndex, occupancyMapClipCount * arrayIndex + cascadeId * BASE_OM_SIZE / 32 * ROMA_COUNT + clipIndex)] | result;
                _RWROMA[uint3(pixelIndex, occupancyMapClipCount * arrayIndex + cascadeId * BASE_OM_SIZE / 32 * ROMA_COUNT + clipIndex)] = currentValue;
            }
        }
    }
}

//[numthreads(16, 16, 1)]
//void GenerateROMA(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
//{
//    const uint occupancyMapSize = (uint) _CascadeResolution.z;
//    const uint occupancyMapClipCount = occupancyMapSize / 32;
    
//    const uint2 pixelIndex = threadId.xy;
//    const uint arrayIndex = _UpdateFrame * _UpdateOMPerFrame + threadId.z;
//    const float4x4 invViewProjMat = _DirectionParamsArray[arrayIndex + _CascadeIndex * ROMA_COUNT].invViewProjMat;
    
//    const float2 uv = (pixelIndex + 0.5f) / occupancyMapSize;

//    // Setup a bunch of samples and transform them to base om space
//    const float3 startPosUV = float3(uv, 0.5f / occupancyMapSize);
//    const float3 endPosUV = float3(uv, 1.0f - 0.5f / occupancyMapSize);
//    const float3 startPosWS = positionUVToWS(startPosUV, invViewProjMat);
//    const float3 endPosWS = positionUVToWS(endPosUV, invViewProjMat);

//    float3 curPosBaseUV = positionWSToUV(startPosWS, _BaseOMViewProjMat);
//    const float3 endPosBaseUV = positionWSToUV(endPosWS, _BaseOMViewProjMat);
//    const float3 rayStep = (endPosBaseUV - curPosBaseUV) / (occupancyMapSize - 1.f);
    
//    // Clear data for previous frame
//    for (int i = 0; i < occupancyMapClipCount; i++)
//    {
//        _RWROMA[uint3(pixelIndex, occupancyMapClipCount * arrayIndex + _CascadeIndex * BASE_OM_SIZE / 32 * ROMA_COUNT + i)] = 0;
//    }

//    for (int i = 0; i < occupancyMapSize; i++, curPosBaseUV += rayStep)
//    {
//        if (any(curPosBaseUV < 0) || any(curPosBaseUV > 1))
//            continue;
//        const uint3 baseVoxelIndex = ((floor(curPosBaseUV * occupancyMapSize)) + _CascadeScrolling) % BASE_OM_SIZE;
//        // Get ombits from base om
//        uint baseClipIndex = baseVoxelIndex.z / 32;
//        uint OMbits = _BaseOccupancyMap[uint3(baseVoxelIndex.xy, baseClipIndex + _CascadeIndex * BASE_OM_SIZE / 32)];
        
//        // Check if the bit is occupied
//        uint bitBase = baseVoxelIndex.z % 32;
//        uint occupied = (OMbits << bitBase) >> 31;

//        // Save result
//        if (occupied > 0)
//        {
//            uint clipIndex = i / 32;
//            uint remainder = i % 32;
//            uint result = 1 << (31 - remainder);
//            uint currentValue = _RWROMA[uint3(pixelIndex, occupancyMapClipCount * arrayIndex + _CascadeIndex * BASE_OM_SIZE / 32 * ROMA_COUNT + clipIndex)] | result;
//            _RWROMA[uint3(pixelIndex, occupancyMapClipCount * arrayIndex + _CascadeIndex * BASE_OM_SIZE / 32 * ROMA_COUNT + clipIndex)] = currentValue;
//        }
//    }
//}