#include "../../GICommon.hlsl"
#pragma kernel BuildVoxelPageReleaseIndirectArgs

int3 _VoxelPageCountInXYZ;
int _ThreadCountForPageRelease;

RWStructuredBuffer<int> _RWIndirectArgs;
RWStructuredBuffer<int> _RWVoxelPageFreeList;
RWStructuredBuffer<int> _RWVoxelPageReleaseList;
RWStructuredBuffer<int> _RWPageCountToReleaseCounter;

[numthreads(1, 1, 1)]
void BuildVoxelPageReleaseIndirectArgs(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    int maxPageNum = _VoxelPageCountInXYZ.x * _VoxelPageCountInXYZ.y * _VoxelPageCountInXYZ.z;
    int pointerIndex = maxPageNum; // we use last element as allocator pointer
    
    int freePointer = min(_RWVoxelPageFreeList[pointerIndex], maxPageNum);
    int releasePointer = _RWVoxelPageReleaseList[pointerIndex];
    int pageCountToRelease = releasePointer;

    // build args
    _RWIndirectArgs[0] = ceil(float(pageCountToRelease) / float(_ThreadCountForPageRelease));
    _RWIndirectArgs[1] = 1;
    _RWIndirectArgs[2] = 1;

    // reset pointer
    _RWVoxelPageFreeList[pointerIndex] = freePointer - pageCountToRelease;
    _RWVoxelPageReleaseList[pointerIndex] = 0;

    // copy for next pass
    _RWPageCountToReleaseCounter[0] = pageCountToRelease;
}

// --------------------------------------------------------------------------------------- //
#pragma kernel VoxelPageRelease

StructuredBuffer<int> _PageCountToReleaseCounter;

[numthreads(8, 1, 1)]
void VoxelPageRelease(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    int maxPageNum = _VoxelPageCountInXYZ.x * _VoxelPageCountInXYZ.y * _VoxelPageCountInXYZ.z;
    int pointerIndex = maxPageNum; // we use last element as allocator pointer
    
    int threadIndex = threadId.x;
    int pageCountToRelease = _PageCountToReleaseCounter[0];

    if (threadIndex >= pageCountToRelease)
    {
        return;
    }

    int freeListOffset = _RWVoxelPageFreeList[pointerIndex];
    int writeIndex = freeListOffset + threadIndex;

    int pageId = _RWVoxelPageReleaseList[threadIndex];
    _RWVoxelPageFreeList[writeIndex] = pageId;
}