#include "../../GICommon.hlsl"
#pragma kernel SurfaceInfoUpdate

#define MAX_CARD_PER_MESH 12

int _ObjectCount;
StructuredBuffer<int> _CardInfoWriteOffsetUploadBuffer;
StructuredBuffer<CardInfo> _CardInfoUploadBuffer;
RWStructuredBuffer<CardInfo> _RWCardInfoBuffer;

[numthreads(8, 1, 1)]
void SurfaceInfoUpdate(uint3 threadId : SV_DispatchThreadID)
{
    int index = threadId.x;
    if (index >= _ObjectCount)
        return;

    int cardReadOffset = index * MAX_CARD_PER_MESH;
    int cardWriteOffset = _CardInfoWriteOffsetUploadBuffer[index];

    for (int cardIndex = 0; cardIndex < MAX_CARD_PER_MESH; cardIndex++)
    {
        _RWCardInfoBuffer[cardWriteOffset + cardIndex] = _CardInfoUploadBuffer[cardReadOffset + cardIndex];
    }
}