#include "../VoxelLighting/VoxelLightingParameters.hlsl"
#include "../RayTracing/MonteCarlo.hlsl"
#include "../RayTracing/SSRTRayCast.hlsl"

// -------------------------------------------------------------------------------- //
float4 _ScreenResolution;
float4 _CameraPosition;
float4x4 _ProjMat;
float4x4 _TranslatedWorldToClip;
float4x4 _ViewProjMat;
float4x4 _InvViewProjMat;
int _FrameCountMod8;
float4 _ZBufferParam;
float4x4 _InvProjMat;
float4x4 _InvViewMat;

float3 ReconstructWorldPositionFromDepth(float2 uv, float depth)
{
    float reverseDepth = 1 - depth;
    float eyeDepth = 1.0 / (_ZBufferParam.z * reverseDepth + _ZBufferParam.w);
    float4 clipPos = float4(uv * 2.0 - 1.0, reverseDepth * 2.0 - 1.0, 1.0);
    float4 viewPos = mul(_InvProjMat, clipPos);
    viewPos /= viewPos.w;
    
    float4 worldPos = mul(_InvViewMat, viewPos);
    
    return worldPos.xyz;
}

float4 SetupPixelRandom(float2 uv)
{
    uint2 randomSeed = Rand3DPCG16(uint3(uv * 1145.14, _FrameCountMod8)).xy;
    float2 E1 = Hammersley16(0, 2, randomSeed);
    float2 E2 = Hammersley16(1, 2, randomSeed);

    return float4(E1, E2);
}

float4 SetupRay(float3 worldNormal, float2 E)
{
    float3x3 tangentBasis = GetTangentBasis(worldNormal);
    float4 tangentL = UniformSampleHemisphere(E);
    float3 rayDirection = mul(tangentL.xyz, tangentBasis);
    float samplePDF = max(tangentL.w, 1e-3);
    
    return float4(rayDirection, samplePDF);
}

// -------------------------------------------------------------------------------- //
#pragma kernel InitialSampleScreenTrace

#define DEBUG_AS_SSR 0
#define FORCE_VOXEL_TRACE 0
#define TILE_SIZE uint2(8, 8)

SamplerState sampler_PointClamp;

float4 _ScreenPositionScaleBias;
float4 _PrevScreenPositionScaleBias;
float4x4 _ClipToPrevClip;
int2 _ScreenGatherRTSize;
float4 _HZBUvFactorAndInvFactor;

Texture2D<float4> _GBufferNormal;
Texture2D<float> _SceneDepthTexture;

Texture2D _HZB;
Texture2D<float4> _SceneColorHistory;
RWTexture2D<float4> _RWHitRadianceTexture;

RWStructuredBuffer<int> _RWVoxelTraceRayCounter;
RWStructuredBuffer<int2> _RWVoxelTraceRayCompactBuffer;

groupshared bool gs_PixelValidMask[64];
groupshared bool gs_ScreenHitMask[64];
groupshared int gs_CompactBufferWriteIndex[64];

[numthreads(8, 8, 1)]
void InitialSampleScreenTrace(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    // 1. do some setup
    const int groupThreadIndex = Index2DTo1D(threadId.xy % TILE_SIZE, TILE_SIZE);
    const bool isValidPixel = all(threadId.xy < _ScreenGatherRTSize - 1);
    const int2 pixelCoord = clamp(threadId.xy, 0, _ScreenGatherRTSize - 1);
    const float2 uv = (float2(pixelCoord) + 0.5) / float2(_ScreenGatherRTSize);

    // 2. setup ray
    float rawDepth = _SceneDepthTexture.SampleLevel(sampler_PointClamp, uv, 0).r;
    float3 worldPosition = ReconstructWorldPositionFromDepth(uv, rawDepth);
    float3 viewDirection = normalize(worldPosition - _CameraPosition);
    float3 rayOriginTranslatedWorld = worldPosition - _CameraPosition;

    float3 worldNormal = _GBufferNormal.SampleLevel(sampler_linearClamp, uv, 0).xyz;
    
    float4 randomVector = SetupPixelRandom(uv);
    float3 rayDirection = SetupRay(worldNormal, randomVector.xy).xyz;

#if DEBUG_AS_SSR
    rayDirection = reflect(viewDirection, worldNormal);
#endif

    // 3. trace screen ray
    const int numSteps = 32;
    float3 hitUVz = float3(0, 0, 0);
    float hitLevel = 0;

    bool isHit = RayCast(
        _HZB, sampler_PointClamp,
        rayOriginTranslatedWorld, rayDirection,
        0.05, // roughness 
        1.0 / (_ZBufferParam.z * (1.0 - rawDepth) + _ZBufferParam.w),
        numSteps,
        randomVector.z, // SSRStepOffset
        _HZBUvFactorAndInvFactor,
        false, // debug print
        _TranslatedWorldToClip, _ProjMat,
        _ScreenPositionScaleBias,
        hitUVz, hitLevel
    );

#if FORCE_VOXEL_TRACE
    isHit = false;
#endif

    // 4. fetch radiance
    float3 color = float3(0, 0, 0);
    if (isHit)
    {
        float2 sampleUV;
        float vignette;
        ReprojectHit(_PrevScreenPositionScaleBias, hitUVz, _ScreenPositionScaleBias, _ClipToPrevClip, sampleUV, vignette);
        color = _SceneColorHistory.SampleLevel(sampler_linearClamp, sampleUV.xy, 0).rgb;
    }

    if (isValidPixel)
    {
        float3 rayEndPosition = ReconstructWorldPositionFromDepth(hitUVz.xy, hitUVz.z);
        float rayDistance = length(rayEndPosition - worldPosition);
        _RWHitRadianceTexture[pixelCoord] = float4(color, rayDistance);
    }

    gs_PixelValidMask[groupThreadIndex] = isValidPixel;
    gs_ScreenHitMask[groupThreadIndex] = isHit;

    GroupMemoryBarrierWithGroupSync();

    // 5. single head thread count missing ray for off screen voxel trace
    if (groupThreadIndex == 0)
    {
        // 5.1. count ray
        int rayCounter = 0;
        for (int i = 0; i < 64; i++)
        {
            if (!gs_ScreenHitMask[i] && gs_PixelValidMask[i])
            {
                rayCounter += 1;
            }
        }
        
        // 5.2. allocate space in compact buffer
        int writeIndex = 0;
        InterlockedAdd(_RWVoxelTraceRayCounter[0], rayCounter, writeIndex);

        // 5.3. boardcast thread write index
        for (int i = 0; i < 64; i++)
        {
            if (!gs_ScreenHitMask[i] && gs_PixelValidMask[i])
            {
                gs_CompactBufferWriteIndex[i] = writeIndex;
                writeIndex += 1;
            }
        }
    }

    GroupMemoryBarrierWithGroupSync();

    // 6. write pixel info to buffer
    if (!isHit && isValidPixel)
    {
        int writeIndex = gs_CompactBufferWriteIndex[groupThreadIndex];
        _RWVoxelTraceRayCompactBuffer[writeIndex] = pixelCoord;
    }
}

// -------------------------------------------------------------------------------- //
#pragma kernel BuildVoxelTraceIndirectArgs

int _NumThreadsForVoxelTrace;
StructuredBuffer<int> _VoxelTraceRayCounter;
RWStructuredBuffer<int> _RWIndirectArgs;

[numthreads(1, 1, 1)]
void BuildVoxelTraceIndirectArgs(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    _RWIndirectArgs[0] = ceil(float(_VoxelTraceRayCounter[0]) / float(_NumThreadsForVoxelTrace));
    _RWIndirectArgs[1] = 1;
    _RWIndirectArgs[2] = 1;
}

// -------------------------------------------------------------------------------- //
#pragma kernel InitialSampleVoxelTrace

StructuredBuffer<int2> _VoxelTraceRayCompactBuffer;

[numthreads(64, 1, 1)]
void InitialSampleVoxelTrace(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    ClipmapInfo clipmapInfo = ResolveClipmapInfo();

    int rayCount = _VoxelTraceRayCounter[0];
    if (threadId.x >= rayCount)
    {
        return;
    }

    int2 pixelCoord = _VoxelTraceRayCompactBuffer[threadId.x];
    const float2 uv = (float2(pixelCoord) + 0.5) / float2(_ScreenGatherRTSize);

    // 1. rebuild tracing context
    float rawDepth = _SceneDepthTexture.SampleLevel(sampler_PointClamp, uv, 0).r;
    float3 worldPosition = ReconstructWorldPositionFromDepth(uv, rawDepth);
    float3 viewDirection = normalize(worldPosition - _CameraPosition);
    
    float3 worldNormal = _GBufferNormal.SampleLevel(sampler_linearClamp, uv, 0).xyz;
    
    float4 randomVector = SetupPixelRandom(uv);
    float3 rayDirection = SetupRay(worldNormal, randomVector.xy).xyz;
    float rayDistance = _RWHitRadianceTexture[pixelCoord].w;

    float3 voxelCellSize = GetVoxelCellSize(clipmapInfo, worldPosition);
    float3 rayStart = worldPosition + worldNormal * voxelCellSize * sqrt(3.0);

    // 2. trace ray
    VoxelRaytracingRequest RTRequest = (VoxelRaytracingRequest) 0;
    RTRequest.rayStart = rayStart;
    RTRequest.rayDir = rayDirection;
    RTRequest.minCascadeIndex = 0;
    RTRequest.maxCascadeIndex = clipmapInfo.cascadeCount - 1;
    RTRequest.maxStepNum = 114514;
    RTRequest.maxDistance = 191981000;

#if USE_DISTANCE_FIELD
    VoxelRayTracingHitPayload hit = DistanceFieldRaytracing(clipmapInfo, _DistanceFieldClipmap, sampler_linearClamp, RTRequest);
#else
    VoxelRayTracingHitPayload hit = VoxelRaytracing(clipmapInfo, _VoxelBitOccupyClipmap, RTRequest);
#endif

    // 3. handle ray hit
    float3 hitRadiance = float3(0, 0, 0);
    if (hit.isHit)
    {
        hitRadiance = FetchRadianceFromVoxelScene(RTRequest, hit);
        rayDistance = length(hit.position - worldPosition);
    }
    else
    {
        rayDistance = 191981000;
        hitRadiance = float3(1, 1, 1);
    }

    _RWHitRadianceTexture[pixelCoord] = float4(hitRadiance, rayDistance);
}