#include "../VoxelLighting/VoxelLightingParameters.hlsl"
#include "../RayTracing/MonteCarlo.hlsl"
#include "../RayTracing/SSRTRayCast.hlsl"
#include "ReservoirSampling.hlsl"

// -------------------------------------------------------------------------------- //
#define DEBUG_AS_SSR 0
#define FORCE_VOXEL_TRACE 1

uint _FrameNumber;
int2 _ScreenGatherRTSize;

SamplerState sampler_PointClamp;
Texture2D<float4> _NormalDepthTexture;
Texture2D<float4> _NormalDepthHistory;

float4 _ScreenPositionScaleBias;
float4x4 _ClipToPrevClip;

// View Params
float4 _CameraPosition;
float4x4 _ProjMat;
float4x4 _TranslatedWorldToClip;
float4 _ZBufferParam;
float4x4 _InvProjMat;
float4x4 _InvViewMat;

float ConvertFromDeviceZ(float rawDepth)
{
    float reverseDepth = 1 - rawDepth;
    return 1.0 / (_ZBufferParam.z * reverseDepth + _ZBufferParam.w);
}

float3 ReconstructWorldPositionFromDepth(float2 uv, float depth)
{
    float eyeDepth = ConvertFromDeviceZ(depth);
    float4 clipPos = float4(uv * 2.0 - 1.0, (1.0 - depth) * 2.0 - 1.0, 1.0);
    float4 viewPos = mul(_InvProjMat, clipPos);
    viewPos /= viewPos.w;
    
    float4 worldPos = mul(_InvViewMat, viewPos);
    
    return worldPos.xyz;
}

float4 SetupPixelRandom(float2 uv)
{
    uint2 randomSeed1 = Rand3DPCG16(uint3(uv * 1919.114, _FrameNumber)).xy;
    uint2 randomSeed2 = Rand3DPCG16(uint3(uv * 810.514, _FrameNumber)).xy;
    float2 E1 = Hammersley16(0, 1, randomSeed1);
    float2 E2 = Hammersley16(0, 1, randomSeed2);

    return float4(E1, E2);
}

float4 SetupRay(float3 worldNormal, float2 E)
{
    float3x3 tangentBasis = GetTangentBasis(worldNormal);
    float4 tangentL = UniformSampleHemisphere(E);
    float3 rayDirection = mul(tangentBasis, tangentL.xyz);
    float samplePDF = max(tangentL.w, 1e-3);
    
    return float4(rayDirection, samplePDF);
}

float2 ReprojectPixel(float3 uvz)
{
    float2 thisScreen = (uvz.xy - _ScreenPositionScaleBias.wz) / _ScreenPositionScaleBias.xy;
    float4 thisClip = float4(thisScreen, uvz.z, 1);
    float4 prevClip = mul(_ClipToPrevClip, thisClip);
    float2 prevScreen = prevClip.xy / prevClip.w;
    float2 prevUV = prevScreen.xy * _ScreenPositionScaleBias.xy + _ScreenPositionScaleBias.wz;
    return prevUV;
}

struct PixelContext
{
    float3 worldPosition;
    float3 worldNormal;
    float rawDepth;
    float sceneDepth;
    float4 randomVector;
    float4 rayDirection;
};

// per pixel ray trace info shared by multiple pass
PixelContext ResolvePixelContext(float2 uv)
{
    PixelContext pixelCtx = (PixelContext) 0;

    float4 normalDepth = _NormalDepthTexture.SampleLevel(sampler_PointClamp, uv, 0);
    pixelCtx.rawDepth = normalDepth.w;
    pixelCtx.sceneDepth = ConvertFromDeviceZ(pixelCtx.rawDepth);
    pixelCtx.worldPosition = ReconstructWorldPositionFromDepth(uv, pixelCtx.rawDepth);
    pixelCtx.worldNormal = normalDepth.rgb * 2 - 1;
    pixelCtx.randomVector = SetupPixelRandom(uv);
    pixelCtx.rayDirection = SetupRay(pixelCtx.worldNormal, pixelCtx.randomVector.xy);

#if DEBUG_AS_SSR
    float3 viewDirection = normalize(pixelCtx.worldPosition - _CameraPosition);
    pixelCtx.rayDirection.xyz = reflect(viewDirection, pixelCtx.worldNormal);
#endif

    return pixelCtx;
}

float GetPixelPositionAndNormal(float2 uv, inout float3 outPosition, inout float3 outNormal)
{
    float4 normalDepth = _NormalDepthTexture.SampleLevel(sampler_PointClamp, uv, 0);
    outPosition = ReconstructWorldPositionFromDepth(uv, normalDepth.w);
    outNormal = normalDepth.xyz * 2 - 1;
    return ConvertFromDeviceZ(normalDepth.w);
}

float3 ClampNaNs(float3 color)
{
    return -min(-color, 0.0);
}

// -------------------------------------------------------------------------------- //
#pragma kernel NormalDepthDownsample

uint2 _SceneTextureRTSize;

Texture2D<float4> _GBufferNormal;
Texture2D<float> _SceneDepthTexture;
RWTexture2D<float4> _RWNormalDepthTexture;

[numthreads(8, 8, 1)]
void NormalDepthDownsample(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    const int2 pixelCoord = clamp(threadId.xy, 0, _ScreenGatherRTSize - 1);
    const float2 uv = (float2(pixelCoord) + 0.5) / float2(_ScreenGatherRTSize);
    
    float2 sampleCoords[4];
    sampleCoords[0] = min(pixelCoord * 2 + uint2(0, 0), _SceneTextureRTSize - 1);
    sampleCoords[1] = min(pixelCoord * 2 + uint2(0, 1), _SceneTextureRTSize - 1);
    sampleCoords[2] = min(pixelCoord * 2 + uint2(1, 0), _SceneTextureRTSize - 1);
    sampleCoords[3] = min(pixelCoord * 2 + uint2(1, 1), _SceneTextureRTSize - 1);

    float4 samples[4];
    for (uint i = 0; i < 4; ++i)
    {
        samples[i].rgb = _GBufferNormal.Load(uint3(sampleCoords[i], 0)).rgb * 0.5f + 0.5f;
        samples[i].a = _SceneDepthTexture.Load(uint3(sampleCoords[i], 0)).r;
    }
	
    float maxDepth = max(max(samples[0].a, samples[1].a), max(samples[2].a, samples[3].a));

    float4 avgColor = 0.0001f;
    for (uint i = 0; i < 4; ++i)
    {
        float depthA = ConvertFromDeviceZ(samples[i].a);
        float depthB = ConvertFromDeviceZ(maxDepth);
        float weight = saturate(1 - abs(depthA - depthB) * 0.01);
        avgColor += float4(samples[i].rgb, 1) * weight;
    }
    avgColor.rgb /= avgColor.w;

    _RWNormalDepthTexture[threadId.xy] = float4(avgColor.rgb, maxDepth);
}

// -------------------------------------------------------------------------------- //
#pragma kernel InitialSampleScreenTrace

#define TILE_SIZE uint2(8, 8)

float4 _HZBUvFactorAndInvFactor;

Texture2D _HZB;
Texture2D<float4> _SceneColorHistory;
RWTexture2D<float4> _RWInitialSampleRadiance;
RWTexture2D<float4> _RWInitialSampleHitInfo;

RWStructuredBuffer<int> _RWVoxelTraceRayCounter;
RWStructuredBuffer<int2> _RWVoxelTraceRayCompactBuffer;

groupshared bool gs_PixelValidMask[64];
groupshared bool gs_ScreenHitMask[64];
groupshared int gs_CompactBufferWriteIndex[64];

[numthreads(8, 8, 1)]
void InitialSampleScreenTrace(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    // 1. do some setup
    const int groupThreadIndex = Index2DTo1D(threadId.xy % TILE_SIZE, TILE_SIZE);
    const int2 pixelCoord = clamp(threadId.xy, 0, _ScreenGatherRTSize - 1);
    const float2 uv = (float2(pixelCoord) + 0.5) / float2(_ScreenGatherRTSize);
    
    PixelContext pixelCtx = ResolvePixelContext(uv);
    const bool isValidPixel = all(threadId.xy < _ScreenGatherRTSize - 1) && pixelCtx.rawDepth > 0;

    // 2. trace screen ray
    const int numSteps = 32;
    float3 hitUVz = float3(0, 0, 0);
    float hitLevel = 0;
    float3 rayOriginTranslatedWorld = pixelCtx.worldPosition - _CameraPosition;

    bool isHit = RayCast(
        _HZB, sampler_PointClamp,
        rayOriginTranslatedWorld, pixelCtx.rayDirection,
        0.05, // roughness 
        pixelCtx.sceneDepth,
        numSteps,
        pixelCtx.randomVector.z, // SSRStepOffset
        _HZBUvFactorAndInvFactor,
        false, // debug print
        _TranslatedWorldToClip, _ProjMat,
        _ScreenPositionScaleBias,
        hitUVz, hitLevel
    );

#if FORCE_VOXEL_TRACE
    isHit = false;
#endif

    // 3. fetch radiance
    float3 hitRadiance = float3(0, 0, 0);
    float3 hitNormal = float3(0, 0, 0);
    if (isHit)
    {
        float2 sampleUV = ReprojectPixel(hitUVz);
        hitRadiance = _SceneColorHistory.SampleLevel(sampler_linearClamp, sampleUV.xy, 0).rgb;
        hitNormal = _NormalDepthHistory.SampleLevel(sampler_PointClamp, sampleUV.xy, 0).rgb * 2 - 1;
        
        // discard back face hit
        if (dot(hitNormal, pixelCtx.rayDirection) < 0)
        {
            isHit = false;
        }
    }

    if (isValidPixel && isHit)
    {
        _RWInitialSampleRadiance[pixelCoord] = float4(hitRadiance, 1);

        float3 rayEndPosition = ReconstructWorldPositionFromDepth(hitUVz.xy, hitUVz.z);
        float rayDistance = length(rayEndPosition - pixelCtx.worldPosition);
        _RWInitialSampleHitInfo[pixelCoord] = float4(hitNormal * 0.5 + 0.5, rayDistance);
    }
    else
    {
        _RWInitialSampleRadiance[pixelCoord] = float4(0, 0, 0, 0);
        _RWInitialSampleHitInfo[pixelCoord] = float4(0, 0, 0, 0);
    }

    gs_PixelValidMask[groupThreadIndex] = isValidPixel;
    gs_ScreenHitMask[groupThreadIndex] = isHit;

    GroupMemoryBarrierWithGroupSync();

    // 4. single head thread count missing ray for off screen voxel trace
    if (groupThreadIndex == 0)
    {
        // 4.1. count ray
        int rayCounter = 0;
        for (int i = 0; i < 64; i++)
        {
            if (!gs_ScreenHitMask[i] && gs_PixelValidMask[i])
            {
                rayCounter += 1;
            }
        }
        
        // 4.2. allocate space in compact buffer
        int writeIndex = 0;
        InterlockedAdd(_RWVoxelTraceRayCounter[0], rayCounter, writeIndex);

        // 4.3. boardcast thread write index
        for (int i = 0; i < 64; i++)
        {
            if (!gs_ScreenHitMask[i] && gs_PixelValidMask[i])
            {
                gs_CompactBufferWriteIndex[i] = writeIndex;
                writeIndex += 1;
            }
        }
    }

    GroupMemoryBarrierWithGroupSync();

    // 5. write pixel info to buffer
    if (!isHit && isValidPixel)
    {
        int writeIndex = gs_CompactBufferWriteIndex[groupThreadIndex];
        _RWVoxelTraceRayCompactBuffer[writeIndex] = pixelCoord;
    }
}

// -------------------------------------------------------------------------------- //
#pragma kernel BuildVoxelTraceIndirectArgs

int _NumThreadsForVoxelTrace;
StructuredBuffer<int> _VoxelTraceRayCounter;
RWStructuredBuffer<int> _RWIndirectArgs;

[numthreads(1, 1, 1)]
void BuildVoxelTraceIndirectArgs(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    _RWIndirectArgs[0] = ceil(float(_VoxelTraceRayCounter[0]) / float(_NumThreadsForVoxelTrace));
    _RWIndirectArgs[1] = 1;
    _RWIndirectArgs[2] = 1;
}

// -------------------------------------------------------------------------------- //
#pragma kernel InitialSampleVoxelTrace

StructuredBuffer<int2> _VoxelTraceRayCompactBuffer;

[numthreads(64, 1, 1)]
void InitialSampleVoxelTrace(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    ClipmapInfo clipmapInfo = ResolveClipmapInfo();

    int rayCount = _VoxelTraceRayCounter[0];
    if (threadId.x >= rayCount)
    {
        return;
    }

    // 1. rebuild tracing context
    int2 pixelCoord = _VoxelTraceRayCompactBuffer[threadId.x];
    const float2 uv = (float2(pixelCoord) + 0.5) / float2(_ScreenGatherRTSize);
    PixelContext pixelCtx = ResolvePixelContext(uv);
    
    float3 voxelCellSize = GetVoxelCellSize(clipmapInfo, pixelCtx.worldPosition);
    float3 rayStart = pixelCtx.worldPosition + pixelCtx.worldNormal * voxelCellSize * sqrt(3.0);

    // 2. trace ray
    VoxelRaytracingRequest RTRequest = (VoxelRaytracingRequest) 0;
    RTRequest.rayStart = rayStart;
    RTRequest.rayDir = pixelCtx.rayDirection;
    RTRequest.minCascadeIndex = 0;
    RTRequest.maxCascadeIndex = clipmapInfo.cascadeCount - 1;
    RTRequest.maxStepNum = 114514;
    RTRequest.maxDistance = 191981000;

#if USE_DISTANCE_FIELD
    VoxelRayTracingHitPayload hit = DistanceFieldRaytracing(clipmapInfo, _DistanceFieldClipmap, sampler_linearClamp, RTRequest);
#else
    VoxelRayTracingHitPayload hit = VoxelRaytracing(clipmapInfo, _VoxelBitOccupyClipmap, RTRequest);
#endif

    // 3. handle ray hit
    float3 hitRadiance = float3(0, 0, 0);
    float3 hitNormal = float3(0, 0, 0);
    float rayDistance = 0;
    if (hit.isHit)
    {
        hitRadiance = FetchRadianceFromVoxelScene(RTRequest, hit);
        rayDistance = length(hit.position - pixelCtx.worldPosition);
        hitNormal = FetchRadianceFromVoxelScene(RTRequest, hit);
    }
    else
    {
        rayDistance = 191981000;
        hitRadiance = float3(1, 1, 1);
        hitNormal = pixelCtx.rayDirection * -1;
    }

    _RWInitialSampleRadiance[pixelCoord] = float4(hitRadiance, rayDistance);
    _RWInitialSampleHitInfo[pixelCoord] = float4(hitNormal * 0.5 + 0.5, rayDistance);
}

// -------------------------------------------------------------------------------- //
#pragma kernel ReservoirTemporalReuse

Texture2D<float4> _InitialSampleRadiance;
Texture2D<float4> _InitialSampleHitInfo;

Texture2D<float4> _ReservoirDataA;
Texture2D<float4> _ReservoirDataB;
Texture2D<float4> _ReservoirDataC;
Texture2D<float4> _ReservoirDataD;

RWTexture2D<float4> _RWReservoirDataA;
RWTexture2D<float4> _RWReservoirDataB;
RWTexture2D<float4> _RWReservoirDataC;
RWTexture2D<float4> _RWReservoirDataD;

Reservoir FetchReservoir(float2 uv)
{
    float4 rawData[4];
    rawData[0] = _ReservoirDataA.SampleLevel(sampler_PointClamp, uv, 0);
    rawData[1] = _ReservoirDataB.SampleLevel(sampler_PointClamp, uv, 0);
    rawData[2] = _ReservoirDataC.SampleLevel(sampler_PointClamp, uv, 0);
    rawData[3] = _ReservoirDataD.SampleLevel(sampler_PointClamp, uv, 0);
    return DecodeReservoirData(rawData);
}

bool IsUVOutSideScreen(float2 uv)
{
    // note: physical texture size may different with viewport size due to UE editor
    // so max uv boundary decided by ScreenPositionScaleBias, not const 1.0
    //float2 ViewportUV = BufferUVToViewportUV(uv);
    float2 ViewportUV = uv;
    return any(ViewportUV <= 0) || any(ViewportUV >= 1);
}

[numthreads(8, 8, 1)]
void ReservoirTemporalReuse(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    // 1. do some setup
    const int2 pixelCoord = clamp(threadId.xy, 0, _ScreenGatherRTSize - 1);
    const float2 uv = (float2(pixelCoord) + 0.5) / float2(_ScreenGatherRTSize);
    PixelContext pixelCtx = ResolvePixelContext(uv);
    
    if (any(threadId.xy >= _ScreenGatherRTSize) || pixelCtx.rawDepth <= 0)
    {
        _RWReservoirDataA[pixelCoord] = float4(0, 0, 0, 0);
        _RWReservoirDataB[pixelCoord] = float4(0, 0, 0, 0);
        _RWReservoirDataC[pixelCoord] = float4(0, 0, 0, 0);
        _RWReservoirDataD[pixelCoord] = float4(0, 0, 0, 0);
        return;
    }

    // 2. setup reservoir sample for current frame's new sample
    ReservoirSample newSample = (ReservoirSample) 0;
    newSample.radiance = _InitialSampleRadiance.SampleLevel(sampler_PointClamp, uv, 0).rgb;
    newSample.rayStart = pixelCtx.worldPosition;
    newSample.rayStartNormal = pixelCtx.worldNormal;

    float4 hitInfo = _InitialSampleHitInfo.SampleLevel(sampler_PointClamp, uv, 0); // hit normal (xyz) and distance (w)
    newSample.rayEnd = pixelCtx.worldPosition + pixelCtx.rayDirection.xyz * hitInfo.w;
    newSample.rayEndNormal = hitInfo.xyz * 2 - 1;

    // 3. reproject and search 3x3 to find match pixel
    float2 reprojectCenterUV = ReprojectPixel(float3(uv, pixelCtx.rawDepth));
    int2 reprojectCenterCoord = reprojectCenterUV * _ScreenGatherRTSize;

    float minDistance = 11451419.19;
    float2 reprojectUV = reprojectCenterUV;
    int reprojectValidCount = 0;
    const int2 offsets[9] = { int2(-1, -1), int2(-1, 0), int2(-1, 1), int2(0, -1), int2(0, 0), int2(0, 1), int2(1, -1), int2(1, 0), int2(1, 1) };
    for (int i = 0; i < 9; i++)
    {
        int2 neighborPixelCoord = reprojectCenterCoord + offsets[i];
        float2 neighborUV = (float2(neighborPixelCoord) + 0.5) / float2(_ScreenGatherRTSize);
        reprojectValidCount += IsUVOutSideScreen(neighborUV) ? 0 : 1;
        
        // calculate distance between reservoir and current pixel
        float3 neighborPosition = _ReservoirDataC.SampleLevel(sampler_PointClamp, neighborUV, 0).xyz; // see DecodeReservoirData()
        float distance = length(pixelCtx.worldPosition - neighborPosition);

        if (distance < minDistance)
        {
            minDistance = distance;
            reprojectUV = neighborUV;
        }
    }

    // 4. fetch temporal reservoir
    Reservoir temporalReservoir = FetchReservoir(reprojectUV);

    // calculate geometry similarity to decide if we need cleanup reservoir history
    float distance = length(pixelCtx.worldPosition - temporalReservoir.currentSample.rayStart);
    float normalDot = abs(dot(pixelCtx.worldNormal, temporalReservoir.currentSample.rayStartNormal));
    if (distance > 0.5 || reprojectValidCount == 0 || isnan(temporalReservoir.weightSum) || isnan(temporalReservoir.estimatorWeight))
    {
        temporalReservoir = (Reservoir) 0;
    }

    // 5. do temporal reuse
    float targetPDF = EvaluateTargetPDF(newSample, newSample.rayStart, newSample.rayStartNormal);
    float sourcePDF = pixelCtx.rayDirection.w;
    float selectionWeight = targetPDF / sourcePDF;
    
    UpdateReservoir(temporalReservoir, newSample, selectionWeight, pixelCtx.randomVector.w);
    
    ClampSampleNumAndUpdateEstimatorWeight(temporalReservoir, pixelCtx.worldPosition, pixelCtx.worldNormal, 5);

    // 6. write reservoir back to buffer
    float4 reservoirRawData[4];
    EncodeReservoirData(temporalReservoir, reservoirRawData);

    _RWReservoirDataA[pixelCoord] = reservoirRawData[0];
    _RWReservoirDataB[pixelCoord] = reservoirRawData[1];
    _RWReservoirDataC[pixelCoord] = reservoirRawData[2];
    _RWReservoirDataD[pixelCoord] = reservoirRawData[3];
}

// -------------------------------------------------------------------------------- //
#pragma kernel ReservoirSpatialReuse

int _SpatialReuseSampleCount;
float _SpatialReuseSearchRange;

[numthreads(8, 8, 1)]
void ReservoirSpatialReuse(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    // 1. fetch reservoir
    const float2 screenGatherTexelSize = 1.0 / float2(_ScreenGatherRTSize);
    const int2 pixelCoord = threadId.xy;
    const float2 uv = (float2(pixelCoord) + 0.5) * screenGatherTexelSize;
    uint randomSeed = GetSimpleRandomSeed(uv * 1145.14, _FrameNumber);
    
    PixelContext pixelCtx = ResolvePixelContext(uv);
    Reservoir reservoir = FetchReservoir(uv);

    if (any(threadId.xy >= _ScreenGatherRTSize) || pixelCtx.rawDepth <= 0)
    {
        _RWReservoirDataA[pixelCoord] = float4(0, 0, 0, 0);
        _RWReservoirDataB[pixelCoord] = float4(0, 0, 0, 0);
        _RWReservoirDataC[pixelCoord] = float4(0, 0, 0, 0);
        _RWReservoirDataD[pixelCoord] = float4(0, 0, 0, 0);
        return;
    }

    // 2. calculate spatial search range
    // use cur pixel's depth to keep range constant in world space
    float3 worldPositionDDXY = ReconstructWorldPositionFromDepth(uv + screenGatherTexelSize, pixelCtx.rawDepth);
    float3 vectorDDXY = length(pixelCtx.worldPosition - worldPositionDDXY);
    float distanceDDXY = max(max(vectorDDXY.x, vectorDDXY.y), vectorDDXY.z);
    float uvSearchRange = clamp((_SpatialReuseSearchRange / distanceDDXY) * screenGatherTexelSize, 0.02, 0.2);

    // 3. reuse neighbor reservoirs
    for (int i = 0; i < _SpatialReuseSampleCount; i++)
    {
        // 3.1. fetch neighbor
        float2 uvOffset = UniformSampleDisk(float2(SimpleRandom(randomSeed), SimpleRandom(randomSeed)));
        float2 neighborUV = uv + uvOffset * uvSearchRange;
        if (IsUVOutSideScreen(neighborUV))
        {
            continue;
        }

        Reservoir neighborReservoir = FetchReservoir(neighborUV);

        // 3.2. consider geometry similarity
        float3 neighborPixelPosition, neighborPixelNormal;
        GetPixelPositionAndNormal(neighborUV, neighborPixelPosition, neighborPixelNormal);
        
        float3 reusedPath = neighborReservoir.currentSample.rayEnd - pixelCtx.worldPosition;
        float3 neighborPath = neighborReservoir.currentSample.rayEnd - neighborReservoir.currentSample.rayStart;

        float hemisphereDot1 = dot(pixelCtx.worldNormal, reusedPath);
        float hemisphereDot2 = dot(pixelCtx.worldNormal, neighborPath);
        float hemisphereDot3 = dot(neighborReservoir.currentSample.rayStartNormal, neighborPath);
        float normalDot = dot(pixelCtx.worldNormal, neighborPixelNormal);
        if (hemisphereDot1 <= 0 || hemisphereDot2 <= 0 || hemisphereDot3 <= 0 || normalDot < 0.8)
        {
            continue;
        }

        // 3.3. calculate jacobian to scale solid angle (measurement density)
        float neighborPathCosine = dot(normalize(-neighborPath), neighborReservoir.currentSample.rayEndNormal);
        float reusedPathCosine = dot(normalize(-reusedPath), neighborReservoir.currentSample.rayEndNormal);
        float jacobian = (neighborPathCosine * LengthSquare(reusedPath)) / (reusedPathCosine * LengthSquare(neighborPath));

        if (neighborPathCosine <= 0 || reusedPathCosine <= 0)
        {
            continue;
        }

        // 3.4. see other reservoir as one sample, calculate merge weight
        // evaluate neighbor sample's target pdf with current pixel's position and normal
        float targetPDF = EvaluateTargetPDF(neighborReservoir.currentSample, pixelCtx.worldPosition, pixelCtx.worldNormal);
        targetPDF /= clamp(jacobian, 0.1, 10); // clamp to prevent firefly
        float mergeWeight = targetPDF * neighborReservoir.estimatorWeight * neighborReservoir.sampleCount; // p_hat * W * M in paper

        // 3.5. merge reservoir
        // note: UpdateReservoir() will add 1 to NumSamples, but we dont need it, just record origin value here
        int sampleCountOld = reservoir.sampleCount;
        UpdateReservoir(reservoir, neighborReservoir.currentSample, mergeWeight, SimpleRandom(randomSeed));
        
        // accumulate sample num, we repeatedly check neighbor sample N times
        reservoir.sampleCount = sampleCountOld + neighborReservoir.sampleCount;
        
        ClampSampleNumAndUpdateEstimatorWeight(reservoir, pixelCtx.worldPosition, pixelCtx.worldNormal, 500);
    }

    // 4. write reservoir back to buffer
    float4 reservoirRawData[4];
    EncodeReservoirData(reservoir, reservoirRawData);

    _RWReservoirDataA[pixelCoord] = reservoirRawData[0];
    _RWReservoirDataB[pixelCoord] = reservoirRawData[1];
    _RWReservoirDataC[pixelCoord] = reservoirRawData[2];
    _RWReservoirDataD[pixelCoord] = reservoirRawData[3];
}

// -------------------------------------------------------------------------------- //
#pragma kernel ReservoirEvaluateIrradiance

RWTexture2D<float4> _RWScreenGatherOutputTexture;

[numthreads(8, 8, 1)]
void ReservoirEvaluateIrradiance(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    // 1. fetch reservoir
    const int2 pixelCoord = clamp(threadId.xy, 0, _ScreenGatherRTSize - 1);
    const float2 uv = (float2(pixelCoord) + 0.5) / float2(_ScreenGatherRTSize);

    PixelContext pixelCtx = ResolvePixelContext(uv);
    Reservoir reservoir = FetchReservoir(uv);
    
    if (any(threadId.xy >= _ScreenGatherRTSize) || pixelCtx.rawDepth <= 0)
    {
        _RWScreenGatherOutputTexture[pixelCoord] = float4(0, 0, 0, 0);
        return;
    }

    // 2. do RIS estimate
    float3 radiance = reservoir.currentSample.radiance * reservoir.estimatorWeight;
    float3 rayDir = normalize(reservoir.currentSample.rayEnd - pixelCtx.worldPosition);
    float cosTheta = max(dot(rayDir, pixelCtx.worldNormal), 0.0); // clamp to prevent black hole pixel, see EvaluateTargetPDF()

    float3 irradiance = radiance * cosTheta / PI;
    _RWScreenGatherOutputTexture[pixelCoord] = float4(irradiance, 1);
}

// -------------------------------------------------------------------------------- //
#pragma kernel IrradianceTemporalAccumulate

float _TemporalAccumulateWeight;
Texture2D<float4> _IrradianceInput;
Texture2D<float4> _DiffuseIndirectHistory;
RWTexture2D<float4> _RWTemporalAccumulateOutput;

[numthreads(8, 8, 1)]
void IrradianceTemporalAccumulate(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    // 1. setup
    const int2 pixelCoord = clamp(threadId.xy, 0, _ScreenGatherRTSize - 1);
    const float2 uv = (float2(pixelCoord) + 0.5) / float2(_ScreenGatherRTSize);
    PixelContext pixelCtx = ResolvePixelContext(uv);

    if (any(threadId.xy >= _ScreenGatherRTSize) || IsUVOutSideScreen(uv) || pixelCtx.rawDepth <= 0)
    {
        _RWTemporalAccumulateOutput[pixelCoord] = float4(0, 0, 0, 0);
        return;
    }

    float3 currentColor = _IrradianceInput.SampleLevel(sampler_linearClamp, uv, 0).rgb;

    // 2. fetch history
    float2 reprojectUV = ReprojectPixel(float3(uv, pixelCtx.rawDepth));
    float3 historyColor = _DiffuseIndirectHistory.SampleLevel(sampler_linearClamp, reprojectUV, 0).rgb;
    historyColor = ClampNaNs(historyColor);

    // 3. reject history if geometry change
    float4 historyNormalDepth = _NormalDepthHistory.SampleLevel(sampler_PointClamp, reprojectUV, 0);
    float3 historyNormal = historyNormalDepth.xyz * 2 - 1;
    float historySceneDepth = ConvertFromDeviceZ(historyNormalDepth.w);

    float historyWeight = _TemporalAccumulateWeight;
    if (IsUVOutSideScreen(reprojectUV) || dot(historyNormal, pixelCtx.worldNormal) < 0.9 || abs(pixelCtx.sceneDepth - historySceneDepth) > 0.5)
    {
        historyWeight = 0;
    }
    
    float3 color = lerp(currentColor, historyColor, historyWeight);
    _RWTemporalAccumulateOutput[pixelCoord] = float4(color, 1);

    // for debug
    //_RWTemporalAccumulateOutput[pixelCoord] = float4(_IrradianceInput.SampleLevel(sampler_linearClamp, uv, 0).rgb, 1);
}

// -------------------------------------------------------------------------------- //
#pragma kernel IrradianceSpatialAccumulate

float _FilterRadius;

RWTexture2D<float4> _RWSpatialAccumulateOutput;

[numthreads(8, 8, 1)]
void IrradianceSpatialAccumulate(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    // 1. setup
    const float2 screenGatherTexelSize = 1.0 / float2(_ScreenGatherRTSize);
    const int2 pixelCoord = clamp(threadId.xy, 0, _ScreenGatherRTSize - 1);
    const float2 uv = (float2(pixelCoord) + 0.5) / float2(_ScreenGatherRTSize);
    PixelContext pixelCtx = ResolvePixelContext(uv);

    if (any(threadId.xy >= _ScreenGatherRTSize) || IsUVOutSideScreen(uv) || pixelCtx.rawDepth <= 0)
    {
        _RWSpatialAccumulateOutput[pixelCoord] = float4(0, 0, 0, 0);
        return;
    }

    // 2. filter current frame output
    float weightSum = 0;
    float3 colorSum = float3(0, 0, 0);
    const int2 offsets[9] = { int2(0, 0), int2(-1, -1), int2(-1, 0), int2(-1, 1), int2(0, -1), int2(0, 1), int2(1, -1), int2(1, 0), int2(1, 1) };
    const float gaussianWeights[9] = { 0.25, 0.0625, 0.125, 0.0625, 0.125, 0.125, 0.0625, 0.125, 0.0625 };
    for (int i = 0; i < 9; i++)
    {
        float2 neighborUV = uv + offsets[i] * _FilterRadius * screenGatherTexelSize;
        if (IsUVOutSideScreen(neighborUV))
        {
            continue;
        }

        float3 neighborColor = _IrradianceInput.SampleLevel(sampler_linearClamp, neighborUV, 0).rgb;
        neighborColor = ClampNaNs(neighborColor);

        float3 neighborPixelPosition, neighborPixelNormal;
        float neighborDepth = GetPixelPositionAndNormal(neighborUV, neighborPixelPosition, neighborPixelNormal);

        float weight = 1;
        weight *= gaussianWeights[i];
        weight *= exp(-abs(neighborDepth - pixelCtx.sceneDepth) * 0.01);
        weight *= saturate(dot(neighborPixelNormal, pixelCtx.worldNormal));

        colorSum += neighborColor * weight;
        weightSum += weight;
    }
    float3 filterColor = (weightSum > 0) ? (colorSum / weightSum) : 0;

    _RWSpatialAccumulateOutput[pixelCoord] = float4(filterColor, 1);
}

// -------------------------------------------------------------------------------- //
#pragma kernel DiffuseComposite

Texture2D<float4> _GBufferBaseColor;
Texture2D<float4> _DiffuseIndirectTexture;
RWTexture2D<float4> _RWSceneTextureOutputTexture;

[numthreads(8, 8, 1)]
void DiffuseComposite(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    float2 screenGatherTexelSize = rcp(float2(_ScreenGatherRTSize));
    const int2 pixelCoord = clamp(threadId.xy, 0, _SceneTextureRTSize - 1);
    const float2 uv = (float2(pixelCoord) + 0.5) / float2(_SceneTextureRTSize);
    if (any(threadId.xy >= _SceneTextureRTSize))
    {
        return;
    }
    
    float3 worldNormal = _GBufferNormal.SampleLevel(sampler_linearClamp, uv, 0).rgb;
    
    float2 sampleUV[4];
    sampleUV[0] = uv + float2(-0.5f, -0.5f) * screenGatherTexelSize;
    sampleUV[1] = min(uv + float2(0.5f, -0.5f) * screenGatherTexelSize, float2(1.0f, 1.0f));
    sampleUV[2] = min(uv + float2(-0.5f, 0.5f) * screenGatherTexelSize, float2(1.0f, 1.0f));
    sampleUV[3] = min(uv + float2(0.5f, 0.5f) * screenGatherTexelSize, float2(1.0f, 1.0f));

    float weightSum = 1e-3;
    float3 irradianceSum = float3(0, 0, 0);
    for (int i = 0; i < 4; i++)
    {
        float3 irradiance = _DiffuseIndirectTexture.SampleLevel(sampler_linearClamp, sampleUV[i], 0).rgb;
        float4 normalDepth = _NormalDepthTexture.SampleLevel(sampler_linearClamp, sampleUV[i], 0);
        float3 rayStartNormal = normalDepth.xyz * 2 - 1;
        float rayStartSceneDepth = ConvertFromDeviceZ(normalDepth.a);
        float weight = 1.0;
        //weight *= 1.0 / abs(rayStartSceneDepth - _SceneDepthTexture.SampleLevel(sampler_PointClamp, uv, 0).r);
        weight *= saturate(dot(rayStartNormal, worldNormal));

        // use SH and full-screen gbuffer normal to sharpen result
#if 1
        ThreeBandSHVector SHBasis = SHBasisFunction3(rayStartNormal);
        ThreeBandSHVectorRGB irradianceSH;
        irradianceSH.R = MulSH3(SHBasis, irradiance.r);
        irradianceSH.G = MulSH3(SHBasis, irradiance.g);
        irradianceSH.B = MulSH3(SHBasis, irradiance.b);

        ThreeBandSHVector pixelNormalSH = CalcDiffuseTransferSH3(worldNormal, 1);
        irradiance = max(float3(0, 0, 0), DotSH3(irradianceSH, pixelNormalSH));
#endif

        irradianceSum += irradiance * weight;
        weightSum += weight;
    }

    float3 diffuseIndirect = irradianceSum / weightSum;

    float metallic = 0.0f;
    diffuseIndirect *= _GBufferBaseColor.SampleLevel(sampler_linearClamp, uv, 0).rgb * (1.0 - metallic); // @TODO: consider shading models

    _RWSceneTextureOutputTexture[threadId.xy] = float4(ClampNaNs(diffuseIndirect), 1);
}