#include "../../GICommon.hlsl"

int _ProbeResolution;
int3 _ProbeCountInXYZ;
int2 _ProbeCountInAtlasXY;
int _CascadeIndex;
int _CascadeCount;
int3 _CascadeResolution;
float3 _CascadeCenter;
float3 _CascadeSize;
int3 _CascadeMoveOffset;

SamplerState sampler_LinearClamp;
Texture2D<float3> _FarFieldProbeAtlas;

struct FVSToPS
{
    nointerpolation int3 ProbeIndex3D : TEXCOORD0;
    float3 RayDirection : TEXCOORD1;
};

void VisualizeFarFieldProveVS(
	in float4 InPosition : ATTRIBUTE0,
	in uint InstanceId : SV_InstanceID,
    out FVSToPS Output,
	out float4 OutPosition : SV_POSITION
	)
{
    float3 LocalPosition = InPosition.xyz;

    int3 ProbeIndex3D = Index1DTo3D(InstanceId, NumProbesInXYZ);
    float3 ProbeLocation = CalcVoxelCenterPos(ProbeIndex3D, NumProbesInXYZ, VolumeCenter, VolumeCoverRange);
    float3 WorldPosition = ProbeLocation + LocalPosition * 25.0f * pow(2, ClipIndex);

    Output.ProbeIndex3D = ProbeIndex3D;
    Output.RayDirection = normalize(LocalPosition);
    OutPosition = mul(float4(WorldPosition.xyz, 1), View.WorldToClip);
}

void VisualizeFarFieldProvePS(
    in FVSToPS Input,
	out float4 OutColor : SV_Target0
)
{
    int3 ProbeIndex3D = Input.ProbeIndex3D;
    float2 UV = FarFieldProbeAddressMapping(
        Input.RayDirection, ProbeIndex3D, NumProbesInXYZ,
	    NumProbesInAtlasXY, ProbeResolution
    );

    float3 Color = FarFieldProbeAtlas.SampleLevel(LinearSampler, UV, 0).rgb;

    OutColor = float4(Color, 1);
}