#include "../../GICommon.hlsl"
#include "../RayTracing/VoxelRayTracing.hlsl"
#include "../RayTracing/MonteCarlo.hlsl"
#include "ProbeCommon.hlsl"

#pragma kernel PickValidVoxel

int _CascadeIndex;
int3 _CascadeResolution;
int3 _CascadeMoveOffset;
int4 _CheckerBoardInfo;

Texture3D<uint2> _VoxelBitOccupyClipmap;
RWStructuredBuffer<int> _RWValidVoxelCounter;
RWStructuredBuffer<int> _RWValidVoxelBuffer;

groupshared int gs_ThreadVoxelCounter[64];
groupshared int gs_ThreadWriteIndex[64];

[numthreads(4, 4, 4)]
void PickValidVoxel(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    int groupThreadIndex = Index3DTo1D(groupThreadId, int3(4, 4, 4));

    // one thread for one block, use checker board 2x2x2 for average update to 8 frame
    int3 blockIndex = threadId.xyz * _CheckerBoardInfo.w + _CheckerBoardInfo.xyz;
    int3 voxelIndexBase = blockIndex * VOXEL_BLOCK_SIZE;
    int3 clipmapAccessIndex = ClipmapAddressMapping(voxelIndexBase, _CascadeResolution, _CascadeMoveOffset, _CascadeIndex);
    uint2 bitOccupy = _VoxelBitOccupyClipmap[clipmapAccessIndex];

    // 1. count valid voxel
    int voxelCounter = BitCount32(bitOccupy.x) + BitCount32(bitOccupy.y);
    gs_ThreadVoxelCounter[groupThreadIndex] = voxelCounter;

    GroupMemoryBarrierWithGroupSync();

    // 2. allocate space in RWValidVoxelBuffer, boardcast write index to thread
    if (groupThreadIndex == 0)
    {
        int groupVoxelCounter = 0;
        for (int i = 0; i < 64; i++)
        {
            groupVoxelCounter += gs_ThreadVoxelCounter[i];
        }

        int startIndex;
        InterlockedAdd(_RWValidVoxelCounter[0], groupVoxelCounter, startIndex);

        for (int i = 0; i < 64; i++)
        {
            gs_ThreadWriteIndex[i] = startIndex;
            startIndex += gs_ThreadVoxelCounter[i];
        }
    }

    GroupMemoryBarrierWithGroupSync();

    // 3. write voxel index to buffer
    int writeIndex = gs_ThreadWriteIndex[groupThreadIndex];
    for (int i = 0; i < VOXEL_COUNT_PER_BLOCK; i++)
    {
        bool hasVoxel = GetUint64SingleBit(bitOccupy, i);
        if (hasVoxel)
        {
            int3 voxelIndex = voxelIndexBase + Index1DTo3D_4x4x4(i);
            int voxelIndex1D = Index3DTo1D(voxelIndex, _CascadeResolution);
            _RWValidVoxelBuffer[writeIndex] = voxelIndex1D;
            writeIndex += 1;
        }
    }
}

// -------------------------------------------------------------------------------- //
#pragma kernel BuildVoxelLightingIndirectArgs

int _ThreadsCountForVoxelLighting;

StructuredBuffer<int> _ValidVoxelCounter;
RWStructuredBuffer<int> _RWIndirectArgs;

[numthreads(1, 1, 1)]
void BuildVoxelLightingIndirectArgs(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    _RWIndirectArgs[0] = ceil(float(_ValidVoxelCounter[0]) / float(_ThreadsCountForVoxelLighting));
    _RWIndirectArgs[1] = 1;
    _RWIndirectArgs[2] = 1;
}

// -------------------------------------------------------------------------------- //
#pragma kernel VoxelLighting

int3 _VoxelPageCountInXYZ;
int _CascadeCount;
float3 _CascadeCenterArray[MAX_CASCADE_COUNT];
float3 _CascadeSizeArray[MAX_CASCADE_COUNT];
int3 _CascadeMoveOffsetArray[MAX_CASCADE_COUNT];

float4x4 _CameraViewProjectionMatrix;
float3 _MainLightDirection;
float4 _MainLightColor;
float _ShadowRayMaxDistance;
int _ShadowRayBoostClipmapOffset;
int _CSMNumCascades;
float4 _CSMShadowBounds[4];
float4x4 _CSMWorldToShadowMatrices[4];

StructuredBuffer<int> _ValidVoxelBuffer;

SamplerState sampler_PointClamp;

Texture2D<float> _ShadowDepthTexture;

Texture3D<float4> _ProbeIrradianceCache;
Texture3D<float4> _ProbePositionOffsetVolume;

Texture3D<int> _VoxelPageClipmap;
Texture3D<float4> _VoxelPoolBaseColor;
Texture3D<float4> _VoxelPoolNormal;
Texture3D<float4> _VoxelPoolEmissive;

RWTexture3D<float3> _RWVoxelPoolRadiance;

ClipmapInfo ResolveClipmapInfo()
{
    ClipmapInfo clipmapInfo = (ClipmapInfo) 0;
    clipmapInfo.cascadeCount = _CascadeCount;
    clipmapInfo.cascadeResolution = _CascadeResolution;
    clipmapInfo.cascadeCenterArray = _CascadeCenterArray;
    clipmapInfo.cascadeSizeArray = _CascadeSizeArray;
    clipmapInfo.cascadeMoveOffsetArray = _CascadeMoveOffsetArray;
    
    return clipmapInfo;
}

[numthreads(8, 1, 1)]
void VoxelLighting(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    if (threadId.x >= _ValidVoxelCounter[0])
    {
        return;
    }
    
    ClipmapInfo clipmapInfo = ResolveClipmapInfo();
    CascadeInfo cascadeInfo = ResolveCascadeInfo(clipmapInfo, _CascadeIndex);

    // 1. read page data, note that 4x4x4 voxel in same block will share 4x4x4 page data in pool
    int voxelIndex1D = _ValidVoxelBuffer[threadId.x];
    int3 voxelIndex = Index1DTo3D(voxelIndex1D, _CascadeResolution);
    int3 clipmapAccessIndex = ClipmapAddressMapping(voxelIndex, _CascadeResolution, cascadeInfo.moveOffset, _CascadeIndex);
    int voxelPageId = _VoxelPageClipmap.Load(uint4(clipmapAccessIndex, 0)).r;

    if (voxelPageId == PAGE_ID_INVALID)
    {
        return;
    }
    
    // 2. read surface attribute
    int3 indexInPool = PageAddressMapping(voxelPageId, _VoxelPageCountInXYZ, voxelIndex);
    float3 baseColor = _VoxelPoolBaseColor.Load(int4(indexInPool, 0));
    float3 worldNormal = _VoxelPoolNormal.Load(int4(indexInPool, 0)) * 2 - 1;
    float3 emissive = _VoxelPoolEmissive.Load(int4(indexInPool, 0));

    // 3. evaluate directional light shadow
    float mainLightShadow = 1.0;
    float3 voxelPosition = CalcVoxelCenterPos(voxelIndex, _CascadeResolution, cascadeInfo.center, cascadeInfo.size);
    float3 voxelClipPosition = mul(_CameraViewProjectionMatrix, float4(voxelPosition, 1));
    voxelClipPosition.xyz /= voxelClipPosition.b;
    bool isVoxelInFrustum = all(abs(voxelClipPosition.xy) < 1) && voxelClipPosition.z > 0; // voxel may behind camera frustum where csm is invalid

    // 3.1. use whole scene shadow map
    for (int cascadeIndex = 0; cascadeIndex < _CSMNumCascades; cascadeIndex++)
    {
        float4 boundSphere = _CSMShadowBounds[cascadeIndex];
        if (length(voxelPosition - boundSphere.xyz) > boundSphere.w || !isVoxelInFrustum)
        {
            continue;
        }
        
        //float4 shadowPosition = mul(float4(voxelPosition, 1), _CSMWorldToShadowMatrixs[cascadeIndex]);
        float4 shadowPosition = mul(_CSMWorldToShadowMatrices[cascadeIndex], float4(voxelPosition, 1));
        shadowPosition.xyz /= shadowPosition.w;
        shadowPosition.y = 0.5f - shadowPosition.y;
        shadowPosition.z = (shadowPosition.z * 0.5f) + 0.5f;
        float sampleZ = _ShadowDepthTexture.SampleLevel(sampler_PointClamp, shadowPosition.xy, 0).r;
        mainLightShadow *= (shadowPosition.z >= sampleZ);
    }

    // 3.2. trace shadow ray as fallback
    if (!isVoxelInFrustum)
    {
        int rayBoostClipmapOffset = _CascadeIndex < (MAX_CASCADE_COUNT / 2) ? _ShadowRayBoostClipmapOffset : 0;
        float3 positionOffset = worldNormal * cascadeInfo.voxelSize * (1 << rayBoostClipmapOffset); // offset 1 voxel to avoid self shadow

        VoxelRaytracingRequest RTRequest = (VoxelRaytracingRequest) 0;
        RTRequest.rayStart = voxelPosition + positionOffset;
        RTRequest.rayDir = _MainLightDirection;
        RTRequest.maxCascadeIndex = _CascadeCount - 1;
        RTRequest.minCascadeIndex = min(cascadeIndex + rayBoostClipmapOffset, RTRequest.maxCascadeIndex);
        RTRequest.maxStepNum = 128000;
        RTRequest.maxDistance = _ShadowRayMaxDistance;

        VoxelRayTracingHitPayload hit = VoxelRaytracing(clipmapInfo, _VoxelBitOccupyClipmap, RTRequest);
        mainLightShadow = hit.isHit ? 0 : 1;
    }

    // 4. evaluate direct lighting
    for (int face = VOXEL_FACE_FRONT; face <= VOXEL_FACE_BACK; face++)
    {
        float3 radiance = emissive;
        float3 faceNormal = worldNormal * lerp(1, -1, face); // -WorldNormal if back face

        // 4.1. evaluate direct lighting
        radiance += saturate(dot(faceNormal, _MainLightDirection)) * _MainLightColor /** mainLightShadow*/ * baseColor / (3.1415926);

        // TODO: pre-exposure

        // 4.2. evaluate indirect lighting
        float3 probeLighting = ProbeEvaluateIrradiance(
            _ProbeIrradianceCache, _ProbePositionOffsetVolume,
            cascadeInfo, voxelPosition, faceNormal
        );
        radiance += probeLighting * baseColor;

        // 4.3. write result
        int3 writeIndex = TwoSideAddressMapping(indexInPool, face);
        _RWVoxelPoolRadiance[writeIndex] = radiance;
    }    
}

// -------------------------------------------------------------------------------- //
#pragma kernel PickValidProbe

RWStructuredBuffer<int> _RWValidProbeCounter;
RWStructuredBuffer<int> _RWValidProbeBuffer;
RWTexture3D<float4> _RWProbePositionOffsetVolume;

groupshared bool gs_ThreadProbeValidMask[64];

[numthreads(4,4,4)]
void PickValidProbe(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    int groupThreadIndex = Index3DTo1D(groupThreadId, int3(4,4,4));

    // one thread for one block (probe num == block num)
    int3 probeCountInXYZ = _CascadeResolution / VOXEL_BLOCK_SIZE;
    int3 blockIndex = threadId.xyz;
    blockIndex = blockIndex * _CheckerBoardInfo.w + _CheckerBoardInfo.xyz;

    // 1. judge if current (and neighbor) block is empty, if not empty we spawn a probe
    bool isProbeValid = false;
    int3 offsets[7] = { int3(-1, 0, 0), int3(1, 0, 0), int3(0, -1, 0), int3(0, 1, 0), int3(0, 0, -1), int3(0, 0, 1), int3(0, 0, 0) };
    for (int i = 0; i < 7; i++)
    {
        int3 neighborBlockIndex = blockIndex + offsets[i];
        if (any(neighborBlockIndex < 0) || any(neighborBlockIndex >= probeCountInXYZ))
        {
            continue;
        }

        int3 clipmapAccessIndex = ClipmapAddressMapping(neighborBlockIndex * VOXEL_BLOCK_SIZE, _CascadeResolution, _CascadeMoveOffset, _CascadeIndex);
        uint2 bitOccupy = _VoxelBitOccupyClipmap.Load(int4(clipmapAccessIndex, 0)).xy;
        isProbeValid = isProbeValid || any(bitOccupy != 0);
    }
    gs_ThreadProbeValidMask[groupThreadIndex] = isProbeValid;

    GroupMemoryBarrierWithGroupSync();

    // 2. allocate space in RWValidProbeBuffer, boardcast write index to thread
    if (groupThreadIndex == 0)
    {
        int probeCounter = 0;
        for (int i = 0; i < 64; i++)
        {
            if (gs_ThreadProbeValidMask[i])
            {
                probeCounter += 1;
            }
        }

        int startIndex;
        InterlockedAdd(_RWValidProbeCounter[0], probeCounter, startIndex);

        for (int i = 0; i < 64; i++)
        {
            if (gs_ThreadProbeValidMask[i])
            {
                gs_ThreadWriteIndex[i] = startIndex;
                startIndex += 1;
            }
        }
    }

    GroupMemoryBarrierWithGroupSync();

    // 3. write probe index to buffer
    int writeIndex = gs_ThreadWriteIndex[groupThreadIndex];
    if (isProbeValid)
    {
        int3 blockCountInXYZ = _CascadeResolution / VOXEL_BLOCK_SIZE;
        _RWValidProbeBuffer[writeIndex] = Index3DTo1D(blockIndex, blockCountInXYZ);
    }
    
    // 4. probe relocation, we find a place where has no voxel, spawn a probe
    int3 probeVolumeAccessIndex = (blockIndex + _CascadeMoveOffset) % probeCountInXYZ;
    if (isProbeValid)
    {
        int3 clipmapAccessIndex = ClipmapAddressMapping(blockIndex * VOXEL_BLOCK_SIZE, _CascadeResolution, _CascadeMoveOffset, _CascadeIndex);
        uint2 bitOccupy = _VoxelBitOccupyClipmap.Load(int4(clipmapAccessIndex, 0)).xy;

        float3 probeCenter = float(VOXEL_BLOCK_SIZE / 2).xxx - 0.5; // 1.5 is center of [0, 1, 2, 3], unit is voxel
        int3 probeOffset = int3(0, 0, 0);
        float minDistance = 128000.0f;

        // find a place near to block center to minimize the offset
        for (int i = 0; i < VOXEL_COUNT_PER_BLOCK; i++)
        {
            bool hasVoxel = GetUint64SingleBit(bitOccupy, i);
            if (hasVoxel)
                continue;

            int3 voxelIndexInBlock = Index1DTo3D_4x4x4(i);
            float distanceToCenter = length(voxelIndexInBlock - probeCenter);
            if (distanceToCenter < minDistance)
            {
                minDistance = distanceToCenter;
                probeOffset = voxelIndexInBlock;
            }
        }

        // xyz is encoded offset, w is valid probe mask
        _RWProbePositionOffsetVolume[probeVolumeAccessIndex] = float4(float3(probeOffset) / VOXEL_BLOCK_SIZE, 1);
    }
    else
    {
        _RWProbePositionOffsetVolume[probeVolumeAccessIndex] = float4(0, 0, 0, 0);
    }
}

// -------------------------------------------------------------------------------- //
#pragma kernel RadianceProbeAllocate

groupshared int gs_SharedProbeState[64];
groupshared int gs_SharedReadWriteIndex[64];

int _RadianceProbeCount;

RWStructuredBuffer<int> _RWRadianceProbeAllocator;
RWStructuredBuffer<int> _RWRadianceProbeFreeList;
RWStructuredBuffer<int> _RWRadianceProbeReleaseList;

RWTexture3D<int> _RWRadianceProbeIdVolume;

[numthreads(4, 4, 4)]
void RadianceProbeAllocate(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    int groupThreadIndex = Index3DTo1D(groupThreadId, int3(4, 4, 4));

    // one thread for one block (probe num == block num)
    int3 probeCountInXYZ = _CascadeResolution / VOXEL_BLOCK_SIZE;
    int3 probeIndex3D = threadId.xyz;
    probeIndex3D = probeIndex3D * _CheckerBoardInfo.w + _CheckerBoardInfo.xyz;

    // 1. mark probe state
    int3 probeVolumeAccessIndex = (probeIndex3D + _CascadeMoveOffset) % probeCountInXYZ;
    bool hasProbe = _ProbePositionOffsetVolume[probeVolumeAccessIndex].w > 0;
    int probeIdInAtlas = _RWRadianceProbeIdVolume[probeVolumeAccessIndex];
    int probeState = PROBE_STATE_DO_NOTHING;

    // if has probe but no space in atlas, we allocate space for it
    if (hasProbe && probeIdInAtlas == PROBE_ID_INVALID)
    {
        probeState = PROBE_STATE_NEED_ADD;
    }
    // if no probe but remain space allocation, we release the space in atlas
    else if (!hasProbe && probeIdInAtlas != PROBE_ID_INVALID)
    {
        probeState = PROBE_STATE_NEED_RELEASE;
    }

    gs_SharedProbeState[groupThreadIndex] = probeState;

    GroupMemoryBarrierWithGroupSync();

    // 2. head thread allocate space for each probe
    if (groupThreadIndex == 0)
    {
        int probeAddCounter = 0;
        int probeReleaseCounter = 0;
        for (int i = 0; i < 64; i++)
        {
            probeAddCounter += (gs_SharedProbeState[i] == PROBE_STATE_NEED_ADD) ? 1 : 0;
            probeReleaseCounter += (gs_SharedProbeState[i] == PROBE_STATE_NEED_RELEASE) ? 1 : 0;
        }

        int addProbeStartIndex = 0;
        InterlockedAdd(_RWRadianceProbeAllocator[FREE_PROBE_POINTER], probeAddCounter, addProbeStartIndex);

        int releaseProbeStartIndex = 0;
        InterlockedAdd(_RWRadianceProbeAllocator[RELEASE_PROBE_POINTER], probeReleaseCounter, releaseProbeStartIndex);

        // boardcast read write index to each thread
        for (int i = 0; i < 64; i++)
        {
            if (gs_SharedProbeState[i] == PROBE_STATE_NEED_ADD)
            {
                gs_SharedReadWriteIndex[i] = addProbeStartIndex;
                addProbeStartIndex += 1;
            }
            if (gs_SharedProbeState[i] == PROBE_STATE_NEED_RELEASE)
            {
                gs_SharedReadWriteIndex[i] = releaseProbeStartIndex;
                releaseProbeStartIndex += 1;
            }
        }
    }

    GroupMemoryBarrierWithGroupSync();

    // 3. fetch free probe id from free list
    if (probeState == PROBE_STATE_NEED_ADD)
    {
        int freeListReadIndex = gs_SharedReadWriteIndex[groupThreadIndex];

        if (freeListReadIndex < _RadianceProbeCount)
        {
            probeIdInAtlas = _RWRadianceProbeFreeList[freeListReadIndex];
        }
    }

    // 4. write probe id to release list
    if (probeState == PROBE_STATE_NEED_RELEASE)
    {
        int releaseListWriteIndex = gs_SharedReadWriteIndex[groupThreadIndex];
        _RWRadianceProbeReleaseList[releaseListWriteIndex] = probeIdInAtlas;
        probeIdInAtlas = PROBE_ID_INVALID;
    }

    // 5. update probe id in volume
    if (probeState != PROBE_STATE_DO_NOTHING)
    {
        _RWRadianceProbeIdVolume[probeVolumeAccessIndex] = probeIdInAtlas;
    }
}

// -------------------------------------------------------------------------------- //
#pragma kernel BuildRadianceProbeReleaseAndCaptureIndirectArgs

int _RadianceProbeResolution;
int _ThreadCountForProbeRelease;
int2 _ThreadCountForProbeCapture;

StructuredBuffer<int> _ValidProbeCounter;

RWStructuredBuffer<int> _RWProbeReleaseIndirectArgs;
RWStructuredBuffer<int> _RWProbeCaptureIndirectArgs;

[numthreads(1, 1, 1)]
void BuildRadianceProbeReleaseAndCaptureIndirectArgs(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    int3 probeCountInXYZ = _CascadeResolution / VOXEL_BLOCK_SIZE;

    // 1. build indirect args for atlas space release
    int freePointer = min(_RWRadianceProbeAllocator[FREE_PROBE_POINTER], _RadianceProbeCount);
    int releasePointer = _RWRadianceProbeAllocator[RELEASE_PROBE_POINTER];
    int probeCountToRelease = releasePointer;

    _RWProbeReleaseIndirectArgs[0] = ceil(float(probeCountToRelease) / float(_ThreadCountForProbeRelease));
    _RWProbeReleaseIndirectArgs[1] = 1;
    _RWProbeReleaseIndirectArgs[2] = 1;

    // 2. reset pointer
    _RWRadianceProbeAllocator[FREE_PROBE_POINTER] = freePointer - probeCountToRelease;
    _RWRadianceProbeAllocator[RELEASE_PROBE_POINTER] = 0;

    // 3. copy for probe release pass
    _RWRadianceProbeAllocator[FREE_PROBE_POINTER_READ_ONLY] = freePointer;
    _RWRadianceProbeAllocator[RELEASE_PROBE_POINTER_READ_ONLY] = releasePointer;
    
    // 4. build indirect args for radiance probe capture
    int probeCountToCapture = _ValidProbeCounter[0];
    int3 groupCountNeeded = int3(
        ceil(float(_RadianceProbeResolution) / float(_ThreadCountForProbeCapture.x)),
        ceil(float(_RadianceProbeResolution) / float(_ThreadCountForProbeCapture.y)),
        probeCountToCapture
    );
    _RWProbeCaptureIndirectArgs[0] = groupCountNeeded.x;
    _RWProbeCaptureIndirectArgs[1] = groupCountNeeded.y;
    _RWProbeCaptureIndirectArgs[2] = groupCountNeeded.z;
}

// ---------------------------------------- (^^_) ---------------------------------------- //
#pragma kernel RadianceProbeRelease

[numthreads(8, 1, 1)]
void RadianceProbeRelease(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    int threadIndex = threadId.x;
    int probeCountToRelease = _RWRadianceProbeAllocator[RELEASE_PROBE_POINTER_READ_ONLY];

    if (threadIndex >= probeCountToRelease)
    {
        return;
    }

    int freeListOffset = _RWRadianceProbeAllocator[FREE_PROBE_POINTER];
    int writeIndex = freeListOffset + threadIndex;

    int pageId = _RWRadianceProbeReleaseList[threadIndex];
    _RWRadianceProbeFreeList[writeIndex] = pageId;
}

// -------------------------------------------------------------------------------- //
#pragma kernel RadianceProbeCapture

groupshared int3 gs_SharedProbeIndex3D;
groupshared float3 gs_SharedProbePosition;
groupshared int3 gs_SharedProbeVolumeAccessIndex;
groupshared int gs_SharedProbeIdInAtlas;

// int RadianceProbeResolution;
int2 _RadianceProbeCountInAtlasXY;

StructuredBuffer<int> _ValidProbeBuffer;

SamplerState sampler_linearClamp;

Texture3D<int> _RadianceProbeIdVolume;
Texture3D<float3> _VoxelPoolRadiance;
RWTexture2D<float3> _RWRadianceProbeAtlas;

int2 RedirectBorderPixel(int2 pixelIndexInProbe)
{
    int2 result = pixelIndexInProbe;
    int pixelIndexMax = _RadianceProbeResolution - 1;

    // row
    if (pixelIndexInProbe.y == 0 || pixelIndexInProbe.y == pixelIndexMax)
    {
        result.x = pixelIndexMax - pixelIndexInProbe.x;
        result.y += (pixelIndexInProbe.y == 0) ? 1 : -1; // top or bottom row
    }
    // col
    if (pixelIndexInProbe.x == 0 || pixelIndexInProbe.x == pixelIndexMax)
    {
        result.x += (pixelIndexInProbe.x == 0) ? 1 : -1; // left or right col
        result.y = pixelIndexMax - pixelIndexInProbe.y;
    }

    // left top
    if (pixelIndexInProbe.x == 0 && pixelIndexInProbe.y == 0)
    {
        result = int2(pixelIndexMax - 1, pixelIndexMax - 1);
    }
    // right top
    if (pixelIndexInProbe.x == pixelIndexMax && pixelIndexInProbe.y == 0)
    {
        result = int2(1, pixelIndexMax - 1);
    }
    // left bottom
    if (pixelIndexInProbe.x == 0 && pixelIndexInProbe.y == pixelIndexMax)
    {
        result = int2(pixelIndexMax - 1, 1);
    }
    // right bottom
    if (pixelIndexInProbe.x == pixelIndexMax && pixelIndexInProbe.y == pixelIndexMax)
    {
        result = int2(1, 1);
    }

    return result;
}

float3 FetchRadianceFromVoxelScene(VoxelRaytracingRequest RTRequest, VoxelRayTracingHitPayload hit)
{
    int voxelPageId = _VoxelPageClipmap.Load(uint4(hit.clipmapAccessIndex, 0)).r;
    if (voxelPageId == PAGE_ID_INVALID)
    {
        return float3(0, 0, 0);
    }

    int3 indexInPool = PageAddressMapping(voxelPageId, _VoxelPageCountInXYZ, hit.voxelIndex);

    float3 worldNormal = _VoxelPoolNormal.Load(uint4(indexInPool, 0)).rgb * 2 - 1;
    int isBackFace = dot(worldNormal, -RTRequest.rayDir) < 0;

    int3 twoSideIndex = TwoSideAddressMapping(indexInPool, isBackFace);
    float3 hitRadiance = _VoxelPoolRadiance.Load(uint4(twoSideIndex, 0)).rgb;

    return hitRadiance;
}

[numthreads(8, 8, 1)]
void RadianceProbeCapture(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    ClipmapInfo clipmapInfo = ResolveClipmapInfo();
    CascadeInfo cascadeInfo = ResolveCascadeInfo(clipmapInfo, _CascadeIndex);

    int3 probeCountInXYZ = _CascadeResolution / VOXEL_BLOCK_SIZE;
    int groupThreadIndex = groupThreadId.x;

    // 1. head thread fetch probe info
    if (groupThreadIndex == 0)
    {
        int probeIndex1D = _ValidProbeBuffer[groupId.z];
        gs_SharedProbeIndex3D = Index1DTo3D(probeIndex1D, probeCountInXYZ);
        gs_SharedProbeVolumeAccessIndex = (gs_SharedProbeIndex3D + cascadeInfo.moveOffset) % probeCountInXYZ;
        gs_SharedProbeIdInAtlas = _RadianceProbeIdVolume[gs_SharedProbeVolumeAccessIndex];

        float3 probePositionBase = CalcVoxelCenterPos(gs_SharedProbeIndex3D, probeCountInXYZ, cascadeInfo.center, cascadeInfo.size);
        float3 probePositionOffsetRaw = _ProbePositionOffsetVolume[gs_SharedProbeVolumeAccessIndex].xyz;
        float3 probePositionOffset = DecodeProbePositionOffset(probePositionOffsetRaw, cascadeInfo.voxelSize);
        gs_SharedProbePosition = probePositionBase + probePositionOffset;
    }

    GroupMemoryBarrierWithGroupSync();

    // 2. calculate octahedral uv and ray direction
    int2 pixelIndexInProbe = threadId.xy % _RadianceProbeResolution; // [0 ~ 16]
    int2 pixelIndexRedirect = RedirectBorderPixel(pixelIndexInProbe);

    float2 probeUV = float2(pixelIndexRedirect - 1) / float(_RadianceProbeResolution - 2); // [0 ~ 1], 2 is for padding
    probeUV += 0.5 / float(_RadianceProbeResolution - 2); // align to texel center
    float3 rayDirection = OctahedralDirection(probeUV);

    // 3. trace ray
    VoxelRaytracingRequest RTRequest = (VoxelRaytracingRequest) 0;
    RTRequest.rayStart = gs_SharedProbePosition;
    RTRequest.rayDir = rayDirection;
    RTRequest.minCascadeIndex = 0; // we start from clip 0 to make sure accuracy when probe fall inside lower clip levels
    RTRequest.maxCascadeIndex = _CascadeCount - 1;
    RTRequest.maxStepNum = 128000;
    RTRequest.maxDistance = 12800000;

    VoxelRayTracingHitPayload hit = VoxelRaytracing(clipmapInfo, _VoxelBitOccupyClipmap, RTRequest);

    // 4. fetch radiance
    float3 hitRadiance = float3(0, 0, 0);
    if (hit.isHit)
    {
        hitRadiance = FetchRadianceFromVoxelScene(RTRequest, hit);
    }
    else
    {
        // TODO: sample skybox
        hitRadiance = float3(1, 1, 1);
        
        // TODO: pre-exposure
    }

    // 5. write to probe atlas
    int2 probeIdInAtlas2D = Index1DTo2D(gs_SharedProbeIdInAtlas, _RadianceProbeCountInAtlasXY);
    int2 writeOffset = probeIdInAtlas2D * _RadianceProbeResolution;
    int2 writeIndex = writeOffset + pixelIndexInProbe;

    _RWRadianceProbeAtlas[writeIndex] = hitRadiance;
}

// -------------------------------------------------------------------------------- //
#pragma kernel BuildIrradianceProbeGatherIndirectArgs

[numthreads(1,1,1)]
void BuildIrradianceProbeGatherIndirectArgs(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    _RWIndirectArgs[0] = _ValidProbeCounter[0];
    _RWIndirectArgs[1] = 1;
    _RWIndirectArgs[2] = 1;
}

// -------------------------------------------------------------------------------- //
#pragma kernel IrradianceProbeGather

int _FrameCountMod8;

//groupshared int gs_ProbeIndex1D;
//groupshared int3 gs_ProbeIndex3D;
//groupshared float3 gs_ProbePosition;
//groupshared int3 gs_ProbeVolumeAccessIndex;
groupshared ThreeBandSHVectorRGB gs_ThreadSHVector[64];

RWTexture3D<float4> _RWProbeIrradianceCache;

float3 SphericalFibonacciSample(float i, float n)
{
    float theta = 2 * PI * i / ((1 + sqrt(5)) * 0.5);
    float phi = acos(1 - 2 * (i) / n);
    return float3(
		sin(phi) * cos(theta),
		sin(phi) * sin(theta),
		cos(phi)
	);
}

[numthreads(64, 1, 1)]
void IrradianceProbeGather(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    ClipmapInfo clipmapInfo = ResolveClipmapInfo();
    CascadeInfo cascadeInfo = ResolveCascadeInfo(clipmapInfo, _CascadeIndex);

    int groupThreadIndex = groupThreadId.x;
    int3 probeCountInXYZ = cascadeInfo.resolution / VOXEL_BLOCK_SIZE;

    // 1. head thread fetch probe info
    if (groupThreadIndex == 0)
    {
        int probeIndex1D = _ValidProbeBuffer[groupId.x];
        gs_SharedProbeIndex3D = Index1DTo3D(probeIndex1D, probeCountInXYZ);
        gs_SharedProbeVolumeAccessIndex = (gs_SharedProbeIndex3D + cascadeInfo.moveOffset) % probeCountInXYZ;
        
        float3 probePositionBase = CalcVoxelCenterPos(gs_SharedProbeIndex3D, probeCountInXYZ, cascadeInfo.center, cascadeInfo.size);
        float3 probePositionOffsetRaw = _ProbePositionOffsetVolume[gs_SharedProbeVolumeAccessIndex].xyz;
        float3 probePositionOffset = DecodeProbePositionOffset(probePositionOffsetRaw, cascadeInfo.voxelSize);
        gs_SharedProbePosition = probePositionBase + probePositionOffset;
    }

    GroupMemoryBarrierWithGroupSync();

    // 2. trace ray
    float uniformSampleSolidAngle = 4 * PI / float(64);
    // float3 rayDirection = SphericalFibonacciSample(groupThreadIndex, 64);
    uint2 randomSeed = Rand3DPCG16(uint3(groupId.x, 0, _FrameCountMod8)).xy;
    float2 E = Hammersley16(groupThreadIndex, 64, randomSeed);
    float3 rayDirection = UniformSampleSphere(E).xyz;

    VoxelRaytracingRequest RTRequest = (VoxelRaytracingRequest) 0;
    RTRequest.rayStart = gs_SharedProbePosition;
    RTRequest.rayDir = rayDirection;
    RTRequest.minCascadeIndex = _CascadeIndex;
    RTRequest.maxCascadeIndex = _CascadeCount - 1;
    RTRequest.maxStepNum = 128000;
    RTRequest.maxDistance = 12800000;

    VoxelRayTracingHitPayload hit = VoxelRaytracing(clipmapInfo, _VoxelBitOccupyClipmap, RTRequest);

    // 3. fetch radiance
    float3 hitRadiance = float3(0, 0, 0);
    if (hit.isHit)
    {
        hitRadiance = FetchRadianceFromVoxelScene(RTRequest, hit);
    }
    else
    {
        // TODO: sample skybox
        hitRadiance = float3(1, 1, 1);
        
        // TODO: pre-exposure
    }

    // 4. SH projection
    ThreeBandSHVector SHBasis = SHBasisFunction3(rayDirection);
    ThreeBandSHVectorRGB SHRadiance;
    SHRadiance.R = MulSH3(SHBasis, hitRadiance.r * uniformSampleSolidAngle);
    SHRadiance.G = MulSH3(SHBasis, hitRadiance.g * uniformSampleSolidAngle);
    SHRadiance.B = MulSH3(SHBasis, hitRadiance.b * uniformSampleSolidAngle);
    gs_ThreadSHVector[groupThreadIndex] = SHRadiance;

    GroupMemoryBarrierWithGroupSync();

    // 5. SH reduction
    for (int reductionSize = (64 / 2); reductionSize >= 1; reductionSize /= 2)
    {
        if (groupThreadIndex < reductionSize)
        {
            gs_ThreadSHVector[groupThreadIndex] = AddSH(gs_ThreadSHVector[groupThreadIndex], gs_ThreadSHVector[groupThreadIndex + reductionSize]);
        }

        GroupMemoryBarrierWithGroupSync();
    }

    // 6. write to volume
    if (groupThreadIndex == 0)
    {
        ThreeBandSHVectorRGB SHSum = gs_ThreadSHVector[0];
        int3 writeIndexBase = gs_SharedProbeVolumeAccessIndex * int3(1, 1, 7);
        
        _RWProbeIrradianceCache[writeIndexBase + int3(0, 0, 0)] = SHSum.R.V0;
        _RWProbeIrradianceCache[writeIndexBase + int3(0, 0, 1)] = SHSum.R.V1;
        _RWProbeIrradianceCache[writeIndexBase + int3(0, 0, 2)] = SHSum.G.V0;
        _RWProbeIrradianceCache[writeIndexBase + int3(0, 0, 3)] = SHSum.G.V1;
        _RWProbeIrradianceCache[writeIndexBase + int3(0, 0, 4)] = SHSum.B.V0;
        _RWProbeIrradianceCache[writeIndexBase + int3(0, 0, 5)] = SHSum.B.V1;
        _RWProbeIrradianceCache[writeIndexBase + int3(0, 0, 6)] = float4(SHSum.R.V2, SHSum.G.V2, SHSum.B.V2, 0);
    }
}