#include "../RayTracing/MonteCarlo.hlsl"
#include "../RayTracing/ROMA.hlsl"
#include "VoxelLightingParameters.hlsl"

#pragma multi_compile _ USE_BOM
#pragma multi_compile _ USE_ROMA
#pragma multi_compile _ RAY_SNAP

// -------------------------------------------------------------------------------- //
#pragma kernel PickValidVoxel

int4 _CheckerBoardInfo;

RWStructuredBuffer<int> _RWValidVoxelCounter;
RWStructuredBuffer<int> _RWValidVoxelBuffer;

groupshared int gs_ThreadVoxelCounter[64];
groupshared int gs_ThreadWriteIndex[64];

[numthreads(4, 4, 4)]
void PickValidVoxel(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    ClipmapInfo clipmapInfo = ResolveClipmapInfo();
    CascadeInfo cascadeInfo = ResolveCascadeInfo(clipmapInfo, _CascadeIndex);
    
    int groupThreadIndex = Index3DTo1D(groupThreadId, int3(4, 4, 4));

    // one thread for one block, use checker board 2x2x2 for average update to 8 frame
    int3 blockIndex = threadId.xyz * _CheckerBoardInfo.w + _CheckerBoardInfo.xyz;
    int3 voxelIndexBase = blockIndex * VOXEL_BLOCK_SIZE;
    int3 clipmapAccessIndex = BlockClipmapAddressMapping(blockIndex, cascadeInfo.resolution, cascadeInfo.scrolling, _CascadeIndex);
    uint2 bitOccupy = _VoxelBitOccupyClipmap[clipmapAccessIndex];

    // 1. count valid voxel
    int voxelCounter = BitCount32(bitOccupy.x) + BitCount32(bitOccupy.y);
    gs_ThreadVoxelCounter[groupThreadIndex] = voxelCounter;

    GroupMemoryBarrierWithGroupSync();

    // 2. allocate space in RWValidVoxelBuffer, boardcast write index to thread
    if (groupThreadIndex == 0)
    {
        int groupVoxelCounter = 0;
        for (int i = 0; i < 64; i++)
        {
            groupVoxelCounter += gs_ThreadVoxelCounter[i];
        }

        int startIndex;
        InterlockedAdd(_RWValidVoxelCounter[0], groupVoxelCounter, startIndex);

        for (int i = 0; i < 64; i++)
        {
            gs_ThreadWriteIndex[i] = startIndex;
            startIndex += gs_ThreadVoxelCounter[i];
        }
    }

    GroupMemoryBarrierWithGroupSync();

    // 3. write voxel index to buffer
    int writeIndex = gs_ThreadWriteIndex[groupThreadIndex];
    for (int i = 0; i < VOXEL_COUNT_PER_BLOCK; i++)
    {
        bool hasVoxel = GetUint64SingleBit(bitOccupy, i);
        if (hasVoxel)
        {
            int3 voxelIndex = voxelIndexBase + Index1DTo3D_4x4x4(i);
            int voxelIndex1D = Index3DTo1D(voxelIndex, cascadeInfo.resolution);
            _RWValidVoxelBuffer[writeIndex] = voxelIndex1D;
            writeIndex += 1;
        }
    }
}

// -------------------------------------------------------------------------------- //
#pragma kernel BuildVoxelLightingIndirectArgs

int _ThreadsCountForVoxelLighting;

StructuredBuffer<int> _ValidVoxelCounter;
RWStructuredBuffer<int> _RWIndirectArgs;

[numthreads(1, 1, 1)]
void BuildVoxelLightingIndirectArgs(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    _RWIndirectArgs[0] = ceil(float(_ValidVoxelCounter[0]) / float(_ThreadsCountForVoxelLighting));
    _RWIndirectArgs[1] = 1;
    _RWIndirectArgs[2] = 1;
}

// -------------------------------------------------------------------------------- //
#pragma kernel VoxelLighting

float4x4 _CameraViewProjectionMatrix;
float3 _MainLightDirection;
float4 _MainLightColor;
int _CSMNumCascades;
float4 _CSMShadowBounds[4];
float4x4 _CSMWorldToShadowMatrices[4];

StructuredBuffer<int> _ValidVoxelBuffer;

SamplerState sampler_PointClamp;

Texture2D<float> _ShadowDepthTexture;

RWTexture3D<float3> _RWVoxelPoolRadiance;

float GetMainLightShadow(in ClipmapInfo clipmapInfo, float3 worldPosition, float3 worldNormal, float3 voxelSize)
{
    float mainLightShadow = 1.0;
    float3 normalBias = worldNormal * voxelSize; // offset to avoid self shadow
    
    float4 voxelClipPosition = mul(_CameraViewProjectionMatrix, float4(worldPosition, 1));
    voxelClipPosition.xyz /= voxelClipPosition.w;
    bool isVoxelInFrustum = all(abs(voxelClipPosition.xy) < 1) && voxelClipPosition.z > 0; // voxel may behind camera frustum where csm is invalid

    
    // @TODO: fix light leaking caused by normal bias
    // 1. use whole scene shadow map
    if (isVoxelInFrustum)
    {
        for (int cascadeIndex = 0; cascadeIndex < _CSMNumCascades; cascadeIndex++)
        {
            float4 boundSphere = _CSMShadowBounds[cascadeIndex];
            if (length(worldPosition - boundSphere.xyz) > boundSphere.w)
            {
                continue;
            }
        
            float4 shadowPosition = mul(_CSMWorldToShadowMatrices[cascadeIndex], float4(worldPosition + normalBias * 4, 1));
            shadowPosition.xyz /= shadowPosition.w;
            float sampleZ = _ShadowDepthTexture.SampleLevel(sampler_PointClamp, shadowPosition.xy, 0).r;
            mainLightShadow *= (shadowPosition.z >= sampleZ);
            break;
        }
    }
    // 2. trace shadow ray as fallback
    else
    {
        VoxelRaytracingRequest RTRequest = (VoxelRaytracingRequest) 0;
        RTRequest.rayStart = worldPosition + normalBias * 0.707;
        RTRequest.rayDir = _MainLightDirection;
        RTRequest.minCascadeIndex = _CascadeIndex;
        RTRequest.maxCascadeIndex = _CascadeCount - 1;
        RTRequest.maxStepNum = 1000;
        RTRequest.maxDistance = 100000;

    // use ROMA to trace shadow ray is not accurate
#if USE_BOM
        VoxelRayTracingHitPayload hit = OccupancyMapRaytracing(clipmapInfo, _BaseOccupancyMap, _BaseOMViewProjMatArray, _BaseOMInvViewProjMatArray, sampler_linearClamp, RTRequest, true);
#elif USE_ROMA
        VoxelRayTracingHitPayload hit = ROMARaytracing(clipmapInfo, _ROMA, _DirectionParamsArray, sampler_linearClamp, RTRequest, true);
#elif USE_DISTANCE_FIELD
        VoxelRayTracingHitPayload hit = DistanceFieldRaytracing(clipmapInfo, _DistanceFieldClipmap, sampler_linearClamp, RTRequest);
#else
        VoxelRayTracingHitPayload hit = VoxelRaytracing(clipmapInfo, _VoxelBitOccupyClipmap, RTRequest);
#endif
        mainLightShadow = hit.isHit ? 0 : 1;
    }
    
    return mainLightShadow;
}

[numthreads(8, 1, 1)]
void VoxelLighting(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    if (threadId.x >= _ValidVoxelCounter[0])
    {
        return;
    }
    
    ClipmapInfo clipmapInfo = ResolveClipmapInfo();
    CascadeInfo cascadeInfo = ResolveCascadeInfo(clipmapInfo, _CascadeIndex);

    // 1. read page data, note that 4x4x4 voxel in same block will share 4x4x4 page data in pool
    int voxelIndex1D = _ValidVoxelBuffer[threadId.x];
    int3 voxelIndex = Index1DTo3D(voxelIndex1D, cascadeInfo.resolution);
    int3 blockIndex = voxelIndex / VOXEL_BLOCK_SIZE;
    int3 clipmapAccessIndex = BlockClipmapAddressMapping(blockIndex, cascadeInfo.resolution, cascadeInfo.scrolling, _CascadeIndex);
    int voxelPageId = _VoxelPageClipmap.Load(uint4(clipmapAccessIndex, 0)).r;

    if (voxelPageId == PAGE_ID_INVALID)
    {
        return;
    }
    
    // 2. read surface attribute
    int3 indexInPool = PageAddressMapping(voxelPageId, _VoxelPageCountInXYZ, voxelIndex);
    float3 baseColor = _VoxelPoolBaseColor.Load(int4(indexInPool, 0));
    float3 worldNormal = _VoxelPoolNormal.Load(int4(indexInPool, 0)) * 2 - 1;
    float3 emissive = _VoxelPoolEmissive.Load(int4(indexInPool, 0));
    float3 voxelPosition = CalcVoxelCenterPos(voxelIndex, cascadeInfo.resolution, cascadeInfo.center, cascadeInfo.size);

    // 3. evaluate direct lighting
    for (int face = VOXEL_FACE_FRONT; face <= VOXEL_FACE_BACK; face++)
    {
        float3 radiance = emissive;
        float3 faceNormal = worldNormal * lerp(1, -1, face); // -WorldNormal if back face

        // 3.1. evaluate direct lighting
        float mainLightShadow = GetMainLightShadow(clipmapInfo, voxelPosition, faceNormal, cascadeInfo.voxelSize);
        // in unity, baseColor includes normalization with PI, therefore we don't need to devide PI here as UE
        radiance += saturate(dot(faceNormal, _MainLightDirection)) * _MainLightColor * mainLightShadow * baseColor /*/ (PI)*/;
        // TODO: pre-exposure
        
        // 3.2. evaluate indirect lighting
        int cascadeIndexForSceneLighting = max(cascadeInfo.cascadeIndex, _IrradianceProbeMinCascadeLevel);
        CascadeInfo cascadeInfoForSceneLighting = ResolveCascadeInfo(clipmapInfo, cascadeIndexForSceneLighting);
        float3 probeLighting = ProbeEvaluateIrradiance(
            _IrradianceProbeClipmap, _ProbeOffsetClipmap,
            _RadianceProbeDistanceAtlas, _RadianceProbeIdClipmap, sampler_linearClamp,
            cascadeInfoForSceneLighting, _RadianceProbeCountInAtlasXY, _RadianceProbeResolution,
            voxelPosition, faceNormal
        );
        radiance += probeLighting * baseColor;

        // 3.3. write result
        int3 writeIndex = TwoSideAddressMapping(indexInPool, face);
        _RWVoxelPoolRadiance[writeIndex] = radiance;
    }    
}

// -------------------------------------------------------------------------------- //                  
#pragma kernel PickValidProbe

RWStructuredBuffer<int> _RWValidProbeCounter;
RWStructuredBuffer<int> _RWValidProbeBuffer;
RWTexture3D<float4> _RWProbeOffsetClipmap;

groupshared bool gs_ThreadProbeValidMask[64];

bool IsProbeInsideFrustum(int3 probeIndex3D, in CascadeInfo cascadeInfo)
{
    int3 probeCountInXYZ = cascadeInfo.resolution / VOXEL_BLOCK_SIZE;
    float3 probePosition = CalcVoxelCenterPos(probeIndex3D, probeCountInXYZ, cascadeInfo.center, cascadeInfo.size);
    
    float4 probeClipPosition = mul(_CameraViewProjectionMatrix, float4(probePosition, 1));
    probeClipPosition.xyz /= probeClipPosition.w;

    bool result = all(abs(probeClipPosition.xy) < 1.1) && probeClipPosition.z > 0;
    return result;
}

[numthreads(4,4,4)]
void PickValidProbe(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    ClipmapInfo clipmapInfo = ResolveClipmapInfo();
    CascadeInfo cascadeInfo = ResolveCascadeInfo(clipmapInfo, _CascadeIndex);
    
    int groupThreadIndex = Index3DTo1D(groupThreadId, int3(4, 4, 4));
    int3 probeCountInXYZ = cascadeInfo.resolution / VOXEL_BLOCK_SIZE;

    // one thread for one block (probe num == block num)
    int3 probeIndex = threadId.xyz;
    probeIndex = probeIndex * _CheckerBoardInfo.w + _CheckerBoardInfo.xyz;

    // 1. judge if current (and neighbor) block is empty, if not empty we spawn a probe
    bool isProbeValid = false;
    int3 offsets[7] = { int3(-1, 0, 0), int3(1, 0, 0), int3(0, -1, 0), int3(0, 1, 0), int3(0, 0, -1), int3(0, 0, 1), int3(0, 0, 0) };
    for (int i = 0; i < 7; i++)
    {
        int3 neighborProbeIndex = probeIndex + offsets[i];
        if (any(neighborProbeIndex < 0) || any(neighborProbeIndex >= probeCountInXYZ))
        {
            continue;
        }

        int3 voxelClipmapAccessIndex = BlockClipmapAddressMapping(neighborProbeIndex, cascadeInfo.resolution, cascadeInfo.scrolling, _CascadeIndex);
        uint2 bitOccupy = _VoxelBitOccupyClipmap[voxelClipmapAccessIndex].xy;
        
        if (any(bitOccupy != 0))
        {
            isProbeValid = true;
            break;
        }
    }
    
    gs_ThreadProbeValidMask[groupThreadIndex] = isProbeValid;

    GroupMemoryBarrierWithGroupSync();

    // 2. allocate space in RWValidProbeBuffer, boardcast write index to thread
    if (groupThreadIndex == 0)
    {
        int probeCounter = 0;
        for (int i = 0; i < 64; i++)
        {
            if (gs_ThreadProbeValidMask[i])
            {
                probeCounter += 1;
            }
        }

        int startIndex;
        InterlockedAdd(_RWValidProbeCounter[0], probeCounter, startIndex);

        for (int i = 0; i < 64; i++)
        {
            if (gs_ThreadProbeValidMask[i])
            {
                gs_ThreadWriteIndex[i] = startIndex;
                startIndex += 1;
            }
        }
    }

    GroupMemoryBarrierWithGroupSync();

    // 3. write probe index to buffer
    int writeIndex = gs_ThreadWriteIndex[groupThreadIndex];
    if (isProbeValid)
    {
        int3 blockCountInXYZ = cascadeInfo.resolution / VOXEL_BLOCK_SIZE;
        _RWValidProbeBuffer[writeIndex] = Index3DTo1D(probeIndex, blockCountInXYZ);
    }
    
    // 4. probe relocation, we find a place where has no voxel, spawn a probe
    int3 probeClipmapAccessIndex = ProbeClipmapAddressMapping(probeIndex, cascadeInfo);
    if (isProbeValid)
    {
        int3 voxelClipmapAccessIndex = BlockClipmapAddressMapping(probeIndex, cascadeInfo.resolution, cascadeInfo.scrolling, _CascadeIndex);
        uint2 bitOccupy = _VoxelBitOccupyClipmap[voxelClipmapAccessIndex].xy;

        float3 probeCenter = float(VOXEL_BLOCK_SIZE / 2).xxx - 0.5; // 1.5 is center of [0, 1, 2, 3], unit is voxel
        int3 probeOffset = int3(0, 0, 0);
        float minDistance = 1000.0f;

        // find a place near to block center to minimize the offset
        for (int i = 0; i < VOXEL_COUNT_PER_BLOCK; i++)
        {
            bool hasVoxel = GetUint64SingleBit(bitOccupy, i);
            if (hasVoxel)
                continue;

            int3 voxelIndexInBlock = Index1DTo3D_4x4x4(i);
            float distanceToCenter = length(voxelIndexInBlock - probeCenter);
            if (distanceToCenter < minDistance)
            {
                minDistance = distanceToCenter;
                probeOffset = voxelIndexInBlock;
            }
        }

        // xyz is encoded offset, w is valid probe mask
        _RWProbeOffsetClipmap[probeClipmapAccessIndex] = float4(float3(probeOffset) / VOXEL_BLOCK_SIZE, 1);
    }
    else
    {
        _RWProbeOffsetClipmap[probeClipmapAccessIndex] = float4(0, 0, 0, 0);
    }
}

// -------------------------------------------------------------------------------- //
#pragma kernel BuildIrradianceProbeGatherIndirectArgs

StructuredBuffer<int> _ValidProbeCounter;

[numthreads(1,1,1)]
void BuildIrradianceProbeGatherIndirectArgs(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    _RWIndirectArgs[0] = _ValidProbeCounter[0];
    _RWIndirectArgs[1] = 1;
    _RWIndirectArgs[2] = 1;
}

// -------------------------------------------------------------------------------- //
#pragma kernel IrradianceProbeGather

int _FrameCountMod8;
int _SampleCount;
int _TemporalWeight;

StructuredBuffer<int> _ValidProbeBuffer;
RWTexture3D<float4> _RWIrradianceProbeClipmap;

groupshared ThreeBandSHVectorRGB gs_SharedSHVector[64];

#ifndef USE_RADIANCE_PROBE_AS_FALLBACK
#define USE_RADIANCE_PROBE_AS_FALLBACK (0)
#endif

[numthreads(32, 1, 1)]
//[numthreads(64, 1, 1)]
void IrradianceProbeGather(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    ClipmapInfo clipmapInfo = ResolveClipmapInfo();
    CascadeInfo cascadeInfo = ResolveCascadeInfo(clipmapInfo, _CascadeIndex);

    int groupThreadIndex = groupThreadId.x;
    int3 probeCountInXYZ = cascadeInfo.resolution / VOXEL_BLOCK_SIZE;

    // 1. head thread fetch probe info
#if !SHARED_PROBE_INFO_FETCH
    int3 gs_SharedProbeIndex3D;
    float3 gs_SharedProbePosition;
    int3 gs_SharedProbeClipmapAccessIndex;
    int gs_SharedProbeIdInAtlas;
#else
    if (groupThreadIndex == 0)
#endif
    {
        int probeIndex1D = _ValidProbeBuffer[groupId.x];
        gs_SharedProbeIndex3D = Index1DTo3D(probeIndex1D, probeCountInXYZ);
        gs_SharedProbeClipmapAccessIndex = ProbeClipmapAddressMapping(gs_SharedProbeIndex3D, cascadeInfo);
        
        float3 probePositionBase = CalcVoxelCenterPos(gs_SharedProbeIndex3D, probeCountInXYZ, cascadeInfo.center, cascadeInfo.size);
        float3 probePositionOffsetRaw = _ProbeOffsetClipmap[gs_SharedProbeClipmapAccessIndex].xyz;
        float3 probePositionOffset = DecodeProbePositionOffset(probePositionOffsetRaw, cascadeInfo.voxelSize);
        gs_SharedProbePosition = probePositionBase + probePositionOffset;
    }

    GroupMemoryBarrierWithGroupSync();

    // 2. trace ray
    int sampleCountPerThread = _SampleCount;
    //int sampleCountPerProbe = 64 * sampleCountPerThread;
    int sampleCountPerProbe = 32 * sampleCountPerThread;
    float uniformSampleSolidAngle = 4 * PI / float(sampleCountPerProbe);
//#if USE_ROMA == 0 || RAY_SNAP == 0
    uint2 randomSeed = Rand3DPCG16(uint3(groupId.x, 0, _FrameCountMod8)).xy;
//#endif
    
    ThreeBandSHVectorRGB SHRadianceSum = (ThreeBandSHVectorRGB) 0;
    for (int i = 0; i < sampleCountPerThread; i++)
    {
        int rayIndex = groupThreadIndex * sampleCountPerThread + i;
//#if USE_ROMA && RAY_SNAP
//        float sign = (rayIndex % 2 == 0) ? 1.0 : -1.0;
 //       float3 rayDirection = normalize(_DirectionParamsArray[rayIndex / 2].viewDir * sign);
//#else
        float2 E = Hammersley16(rayIndex, sampleCountPerProbe, randomSeed);
        float3 rayDirection = UniformSampleSphere(E).xyz;
//#endif

        VoxelRaytracingRequest RTRequest = (VoxelRaytracingRequest) 0;
        RTRequest.rayStart = gs_SharedProbePosition;
        RTRequest.rayDir = rayDirection;
        RTRequest.minCascadeIndex = _CascadeIndex;
        RTRequest.maxCascadeIndex = _CascadeCount - 1;
        RTRequest.maxStepNum = 1000;
        RTRequest.maxDistance = 100000;
    
#if USE_RADIANCE_PROBE_AS_FALLBACK
        RTRequest.maxDistance = GetRadianceProbeSize(cascadeInfo);
#endif
        
#if USE_BOM
        VoxelRayTracingHitPayload hit = OccupancyMapRaytracing(clipmapInfo, _BaseOccupancyMap, _BaseOMViewProjMatArray, _BaseOMInvViewProjMatArray, sampler_linearClamp, RTRequest, false);
#elif USE_ROMA
        //RTRequest.maxStepNum = 20;
        VoxelRayTracingHitPayload hit = ROMARaytracing(clipmapInfo, _ROMA, _DirectionParamsArray, sampler_linearClamp, RTRequest, false);
#elif USE_DISTANCE_FIELD
        VoxelRayTracingHitPayload hit = DistanceFieldRaytracing(clipmapInfo, _DistanceFieldClipmap, sampler_linearClamp, RTRequest);
#else
        VoxelRayTracingHitPayload hit = VoxelRaytracing(clipmapInfo, _VoxelBitOccupyClipmap, RTRequest);
#endif

    // 3. fetch radiance
        float3 hitRadiance = float3(0, 0, 0);
        if (hit.isHit)
        {
            hitRadiance = FetchRadianceFromVoxelScene(RTRequest, hit);
        }
    // hanedle ray miss
        else
        {
#if USE_RADIANCE_PROBE_AS_FALLBACK
            // lower level probe will use upper level's radiance probe as fallback
            int uppderCascadeIndex = max(cascadeInfo.cascadeIndex, _RadianceProbeMinCascadeLevel);
            CascadeInfo cascadeInfoUpper = ResolveCascadeInfo(clipmapInfo, uppderCascadeIndex);
            hitRadiance = ProbeEvaluateRadiance(
                _RadianceProbeAtlas, _RadianceProbeDistanceAtlas, 
                _RadianceProbeIdClipmap, _ProbeOffsetClipmap, sampler_linearClamp,
                cascadeInfo, _RadianceProbeCountInAtlasXY, _RadianceProbeResolution, 
                gs_SharedProbePosition, rayDirection
            );
#else
        // TODO: sample skybox
            hitRadiance = float3(1, 1, 1);
        
        // TODO: pre-exposure
#endif
        }

    // 4. SH projection
        ThreeBandSHVector SHBasis = SHBasisFunction3(rayDirection);
        ThreeBandSHVectorRGB SHRadiance;
        SHRadiance.R = MulSH3(SHBasis, hitRadiance.r * uniformSampleSolidAngle);
        SHRadiance.G = MulSH3(SHBasis, hitRadiance.g * uniformSampleSolidAngle);
        SHRadiance.B = MulSH3(SHBasis, hitRadiance.b * uniformSampleSolidAngle);
        
        SHRadianceSum = AddSH(SHRadianceSum, SHRadiance);
    }
    
    gs_SharedSHVector[groupThreadIndex] = SHRadianceSum;

    GroupMemoryBarrierWithGroupSync();

    // 5. SH reduction
    //for (int reductionSize = (64 / 2); reductionSize >= 1; reductionSize /= 2)
    for (int reductionSize = (32 / 2); reductionSize >= 1; reductionSize /= 2)
    {
        if (groupThreadIndex < reductionSize)
        {
            gs_SharedSHVector[groupThreadIndex] = AddSH(gs_SharedSHVector[groupThreadIndex], gs_SharedSHVector[groupThreadIndex + reductionSize]);
        }

        GroupMemoryBarrierWithGroupSync();
    }

    // 6. write to volume
    if (groupThreadIndex == 0)
    {
        ThreeBandSHVectorRGB SHSum = gs_SharedSHVector[0];
        int3 readWriteIndexBase = gs_SharedProbeClipmapAccessIndex * int3(7, 1, 1);
        
        float4 SHVectorHistory[7];
        for (int i = 0; i < 7; i++)
        {
            SHVectorHistory[i] = _RWIrradianceProbeClipmap[readWriteIndexBase + int3(i, 0, 0)];
        }

        float4 SHVector[7];
        SHVector[0] = SHSum.R.V0;
        SHVector[1] = SHSum.R.V1;
        SHVector[2] = SHSum.G.V0;
        SHVector[3] = SHSum.G.V1;
        SHVector[4] = SHSum.B.V0;
        SHVector[5] = SHSum.B.V1;
        SHVector[6] = float4(SHSum.R.V2, SHSum.G.V2, SHSum.B.V2, 0);

        for (int i = 0; i < 7; i++)
        {
            _RWIrradianceProbeClipmap[readWriteIndexBase + int3(i, 0, 0)] = lerp(SHVector[i], SHVectorHistory[i], _TemporalWeight);
        }
    }
}

// -------------------------------------------------------------------------------- //
#pragma kernel ClearDirtyVoxelRadiance

int3 _UpdateChunkResolution;
StructuredBuffer<int> _UpdateChunkCleanupList;

[numthreads(4, 4, 4)]
void ClearDirtyVoxelRadiance(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    ClipmapInfo clipmapInfo = ResolveClipmapInfo();
    CascadeInfo cascadeInfo = ResolveCascadeInfo(clipmapInfo, _CascadeIndex);

    int3 chunkNumXYZ = cascadeInfo.resolution / _UpdateChunkResolution;
    int chunkIndex = threadId.x / _UpdateChunkResolution.x;
    int chunkId_1D = _UpdateChunkCleanupList[chunkIndex];
    int3 chunkId_3D = Index1DTo3D(chunkId_1D, chunkNumXYZ);
    int3 voxelIndex = chunkId_3D * _UpdateChunkResolution + (threadId % _UpdateChunkResolution);
    int3 blockIndex = voxelIndex / VOXEL_BLOCK_SIZE;

    int3 clipmapAccessIndex = BlockClipmapAddressMapping(blockIndex, cascadeInfo.resolution, cascadeInfo.scrolling, _CascadeIndex);
    int voxelPageId = _VoxelPageClipmap[clipmapAccessIndex].r;
    if (voxelPageId == PAGE_ID_INVALID)
    {
        return;
    }

    int3 indexInPool = PageAddressMapping(voxelPageId, _VoxelPageCountInXYZ, voxelIndex);
    int3 twoSideIndex0 = TwoSideAddressMapping(indexInPool, false);
    int3 twoSideIndex1 = TwoSideAddressMapping(indexInPool, true);

    _RWVoxelPoolRadiance[twoSideIndex0] = float4(0, 0, 0, 0);
    _RWVoxelPoolRadiance[twoSideIndex1] = float4(0, 0, 0, 0);
}

// -------------------------------------------------------------------------------- //
#pragma kernel ClearDirtyProbeIrradiance

[numthreads(4, 4, 4)]
void ClearDirtyProbeIrradiance(uint3 threadId : SV_DispatchThreadID, uint3 groupThreadId : SV_GroupThreadID, uint3 groupId : SV_GroupID)
{
    ClipmapInfo clipmapInfo = ResolveClipmapInfo();
    CascadeInfo cascadeInfo = ResolveCascadeInfo(clipmapInfo, _CascadeIndex);

    int3 blockCountPerUpdateChunk = _UpdateChunkResolution / VOXEL_BLOCK_SIZE;
    int3 chunkNumXYZ = cascadeInfo.resolution / _UpdateChunkResolution;
    int chunkIndex = threadId.x / blockCountPerUpdateChunk;
    int chunkId_1D = _UpdateChunkCleanupList[chunkIndex];
    int3 chunkId_3D = Index1DTo3D(chunkId_1D, chunkNumXYZ);
    int3 blockIndex = (chunkId_3D * _UpdateChunkResolution) / VOXEL_BLOCK_SIZE;

    int3 clipmapAccessIndex = BlockClipmapAddressMapping(blockIndex, cascadeInfo.resolution, cascadeInfo.scrolling, _CascadeIndex);
    int3 readWriteIndexBase = clipmapAccessIndex * int3(7, 1, 1);
    for (int i = 0; i < 7; i++)
    {
        _RWIrradianceProbeClipmap[readWriteIndexBase + int3(i, 0, 0)] = float4(0, 0, 0, 0);
    }
}